In [1]:
import numpy as np
import pandapipes as pp
from pandapipes.control.run_control import run_control as run_control
from pandapipes.pf.pipeflow_setup import get_fluid

In [2]:
net = pp.create_empty_network(fluid="water")

# Nudos de la Central / Fuente
j_fuente_ida = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Fuente_Ida")
j_fuente_ret = pp.create_junction(net, pn_bar=1.5, tfluid_k=333.15, name="Fuente_Retorno")

# Nudos en casa del Consumidor
j_cons_ida = pp.create_junction(net, pn_bar=4.8, tfluid_k=353.15, name="Consumidor_Ida")
j_cons_ret = pp.create_junction(net, pn_bar=1.7, tfluid_k=333.15, name="Consumidor_Retorno")
# j_storage_ida= pp.create_junction(net, pn_bar=4.8, tfluid_k=353.15, name="Storage_Ida")
# j_storage_return= pp.create_junction(net, pn_bar=1.7, tfluid_k=333.15, name="Storage_Retorno")

pipe_ida = pp.create_pipe_from_parameters(
    net, from_junction=j_fuente_ida, to_junction=j_cons_ida,
    length_km=0.1616, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15), k_mm=0.1*1000, text_k=273.2, name="Tubo_Ida"
)

pipe_retorno = pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret, to_junction=j_fuente_ret,
    length_km=0.1616, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15), k_mm=0.1*1000, text_k=273.2, name="Tubo_Retorno"
)

#Fuente 
pp.create_circ_pump_const_pressure(net,flow_junction=j_fuente_ida,return_junction=j_fuente_ret,p_flow_bar=3,plift_bar=0.5,t_flow_k=353 ,name='Grid'
)

pp.create_ext_grid(net, junction=j_cons_ret, t_k=318, type="t", name="Fuente_Externa")
pp.create_source(net, junction=j_cons_ret, mdot_kg_per_s=1.053771, name="Fuente_Externa")
pp.create_sink(net, junction=j_cons_ida, mdot_kg_per_s=1.053771, name="Almacenamiento")

np.int64(0)

In [3]:
pp.pipeflow(net, mode="bidirectional")

In [4]:
net.res_pipe

,v_mean_m_per_s,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s,reynolds,lambda,dp_friction_loss_bar
0,0.061343,3.000000,2.991085,353.0,351.985859,351.985859,1.053771,-1.053771,0.001084,25094.933750,0.452419,0.008915
1,0.060214,2.508784,2.500000,318.0,317.428484,317.428484,1.053771,-1.053771,0.001064,14926.277849,0.454156,0.008784

In [5]:
net.res_circ_pump_pressure

,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s,deltat_k,qext_w
0,2.5,3.0,317.428484,353.0,353.0,1.053771,-1.053771,0.001074,-35.571516,157009.104459

In [6]:
net.res_source

   mdot_kg_per_s
0       1.053771

In [7]:
net.junction

                 name  pn_bar  tfluid_k  height_m  in_service      type
0          Fuente_Ida     5.0    353.15       0.0        True  junction
1      Fuente_Retorno     1.5    333.15       0.0        True  junction
2      Consumidor_Ida     4.8    353.15       0.0        True  junction
3  Consumidor_Retorno     1.7    333.15       0.0        True  junction

In [8]:
net.res_junction

      p_bar         t_k
0  3.000000  353.000000
1  2.500000  317.428484
2  2.991085  351.985859
3  2.508784  318.000000

In [9]:
net.ext_grid

             name  junction  p_bar    t_k  in_service type
0  Fuente_Externa         3    NaN  318.0        True    t