In [96]:
import pandapipes as pp
from tespy.components import Compressor,SimpleHeatExchanger,CycleCloser, Valve, HeatExchanger,Condenser, Sink, Source
from tespy.connections import Connection
from tespy.networks import Network
import numpy as np
from tespy.tools import UserDefinedEquation


class Bidirectional_W_to_WHeatPump:

    def __init__( self,name,net,refrigerant,HC_heat_consumer_id):
        self.name = name
        self.refrigerant = refrigerant
        self.HC_heat_consumer_id=HC_heat_consumer_id
        self.net=net
        self._build_tespy_Cycles()

    def _build_tespy_Cycles(self):
        def my_ude(ude):
            dt_DHN=ude.params['dt']
            return ude.conns[0].calc_T()+dt_DHN-ude.conns[1].calc_T()
        def my_ude_dependents(ude):
            c1, c2 = ude.conns
            return [c1.p,c1.h, c2.p,c2.h]
        self.nw_Cooling_net = Network()
        self.nw_Cooling_net.units.set_defaults(temperature="degC", pressure="bar",pressure_difference="bar",  enthalpy="J/kg", heat="W", power="W")
        self.Cooling_net_compressor = Compressor("compresor")
        self.Cooling_net_condenser = Condenser("condensador")
        self.Cooling_net_valve = Valve("valvula_expansion")
        self.Cooling_net_evaporator = HeatExchanger("evaporador")
        self.Cooling_net_cc=CycleCloser('CycleCloser')
        self.Cooling_net_source_consumer=Source("Source_Consumer ")
        self.Cooling_net_sink_consumer=Sink("Sink_consumer")
        self.Cooling_net_source_reseau=Source("Source_Reseau")
        self.Cooling_net_sink_reseau=Sink("Sink_Reseau")
        self.Cooling_net_c0=Connection(self.Cooling_net_valve, 'out1', self.Cooling_net_cc, 'in1', label='0')
        self.Cooling_net_c1 = Connection(self.Cooling_net_cc, 'out1', self.Cooling_net_evaporator, 'in2', label='1')
        self.Cooling_net_c2 = Connection(self.Cooling_net_evaporator, 'out2', self.Cooling_net_compressor, 'in1', label='2')
        self.Cooling_net_c3 = Connection(self.Cooling_net_compressor, 'out1', self.Cooling_net_condenser, 'in1', label='3')
        self.Cooling_net_c4 = Connection(self.Cooling_net_condenser, 'out1', self.Cooling_net_valve, 'in1', label='4')
        self.Cooling_net_c5=Connection(self.Cooling_net_condenser, 'out2',self.Cooling_net_sink_consumer, 'in1', label='5')
        self.Cooling_net_c6=Connection(self.Cooling_net_source_consumer, 'out1',self.Cooling_net_condenser , 'in2', label='6')
        self.Cooling_net_c7=Connection(self.Cooling_net_source_reseau, 'out1',self.Cooling_net_evaporator , 'in1', label='7')
        self.Cooling_net_c8=Connection(self.Cooling_net_evaporator, 'out1',self.Cooling_net_sink_reseau , 'in1', label='8')
        self.nw_Cooling_net.add_conns(self.Cooling_net_c0,  self.Cooling_net_c1,  self.Cooling_net_c2,  self.Cooling_net_c3,  self.Cooling_net_c4 , self.Cooling_net_c5,  self.Cooling_net_c6, self.Cooling_net_c7, self.Cooling_net_c8)
        self.Cooling_ude = UserDefinedEquation(
                    'my_ude', my_ude, my_ude_dependents, conns=[self.Cooling_net_c8, self.Cooling_net_c7],params={'dt': 5})
        self.nw_Cooling_net.add_ude(self.Cooling_ude)
        
        #Heating net 
        self.nw_Heating_net = Network()
        self.nw_Heating_net.units.set_defaults(temperature="degC", pressure="bar",pressure_difference="bar",  enthalpy="J/kg", heat="W", power="W")
        self.Heating_net_compressor = Compressor("compresor")
        self.Heating_net_condenser = Condenser("condensador")
        self.Heating_net_valve = Valve("valvula_expansion")
        self.Heating_net_evaporator = HeatExchanger("evaporador")
        self.Heating_net_cc=CycleCloser('CycleCloser')
        self.Heating_net_source_consumer=Source("Source_Consumer ")
        self.Heating_net_sink_consumer=Sink("Sink_consumer")
        self.Heating_net_source_reseau=Source("Source_Reseau")
        self.Heating_net_sink_reseau=Sink("Sink_Reseau")
        self.Heating_net_c0=Connection(self.Heating_net_valve, 'out1', self.Heating_net_cc, 'in1', label='0')
        self.Heating_net_c1 = Connection(self.Heating_net_cc, 'out1', self.Heating_net_evaporator, 'in2', label='1')
        self.Heating_net_c2 = Connection(self.Heating_net_evaporator, 'out2', self.Heating_net_compressor, 'in1', label='2')
        self.Heating_net_c3 = Connection(self.Heating_net_compressor, 'out1', self.Heating_net_condenser, 'in1', label='3')
        self.Heating_net_c4 = Connection(self.Heating_net_condenser, 'out1', self.Heating_net_valve, 'in1', label='4')
        self.Heating_net_c5 = Connection(self.Heating_net_evaporator, 'out1', self.Heating_net_sink_consumer, 'in1', label='5')
        self.Heating_net_c6 = Connection(self.Heating_net_source_consumer, 'out1', self.Heating_net_evaporator, 'in1', label='6')  
        self.Heating_net_c7 = Connection(self.Heating_net_source_reseau, 'out1', self.Heating_net_condenser, 'in2', label='7')
        self.Heating_net_c8 = Connection(self.Heating_net_condenser, 'out2', self.Heating_net_sink_reseau, 'in1', label='8')
        self.nw_Heating_net.add_conns(self.Heating_net_c0,  self.Heating_net_c1,  self.Heating_net_c2,  self.Heating_net_c3,  self.Heating_net_c4 , self.Heating_net_c5,  self.Heating_net_c6, self.Heating_net_c7, self.Heating_net_c8)
        self.Heating_ude = UserDefinedEquation(
                        'my_ude_4', my_ude, my_ude_dependents, conns=[self.Heating_net_c7, self.Heating_net_c8],params={'dt': 5})
        self.nw_Heating_net.add_ude(self.Heating_ude)
        
    def solve_cycle(self,mode,Q_consumer,eta_s,T_nework_in,T_cons,dt_DHN):
        #The pressure values for the consumer and district heating side in the heating pump are arbitrary values
        self.mode=mode
        T_cons_in = T_cons[0]
        T_cons_out = T_cons[1]
        T_DH_in = T_nework_in
        if self.mode=="COOLING_NET":
            self.Cooling_net_evaporator.set_attr(pr1=1, pr2=1, ttd_l=5)
            self.Cooling_net_condenser.set_attr(pr1=1, pr2=1, ttd_u=5,Q=Q_consumer)
            self.Cooling_net_compressor.set_attr(eta_s=eta_s)
            self.Cooling_net_c2.set_attr(fluid={self.refrigerant: 1},td_dew=5)
            # 6. Parámetros del Consumidor 
            self.Cooling_net_c5.set_attr(T=T_cons_out, p=3, fluid={"water": 1})
            self.Cooling_net_c6.set_attr(T=T_cons_in)
            # 7. Parámetros de la Red de Distrito (Recibe calor, se calienta de 50 °C a 60 °C)
            self.Cooling_net_c7.set_attr(T=T_DH_in, p=2.5, fluid={"water": 1})
            import CoolProp.CoolProp as CP
            T_triple = CP.Props1SI("Ttriple", self.refrigerant)        # Triple point temperature (K)
            p_triple = CP.Props1SI("ptriple", self.refrigerant)        # Triple point pressure (Pa)
            T_critical = CP.Props1SI("T_critical", self.refrigerant)  # Critical temperature (K)
            p_critical = CP.Props1SI("p_critical", self.refrigerant)  # Critical pressure (Pa)
            h_min = CP.PropsSI("H", "T", T_triple + 0.1, "Q", 0, self.refrigerant)
            T_max_K =  T_critical*0.9
            p_high = min(p_critical * 0.9, 30e5) 
            h_max = CP.PropsSI("H", "T", T_max_K, "P", p_high, self.refrigerant)
            self.nw_Cooling_net._set_p_range([p_triple, p_high])
            self.nw_Cooling_net._set_h_range([h_min,h_max])
            self.Cooling_ude.params['dt'] = dt_DHN
            self.nw_Cooling_net.solve('design')        
        elif self.mode=="HEATING_NET":
            self.Heating_net_evaporator.set_attr(pr1=1, pr2=1, ttd_l=5,Q=Q_consumer)
            self.Heating_net_condenser.set_attr(pr1=1, pr2=1, ttd_u=5)
            self.Heating_net_compressor.set_attr(eta_s=eta_s)
            self.Heating_net_c2.set_attr(fluid={self.refrigerant: 1},td_dew=5)
            # 6. Parámetros del Consumidor 
            self.Heating_net_c5.set_attr(T=T_cons_out, p=3, fluid={"water": 1})
            self.Heating_net_c6.set_attr(T=T_cons_in)
            # 7. Parámetros de la Red de Distrito (Recibe calor, se calienta de 50 °C a 60 °C)
            self.Heating_net_c7.set_attr(T=T_DH_in, p=2.5, fluid={"water": 1})
            import CoolProp.CoolProp as CP
            T_triple = CP.Props1SI("Ttriple", self.refrigerant)        # Triple point temperature (K)
            p_triple = CP.Props1SI("ptriple", self.refrigerant)        # Triple point pressure (Pa)
            T_critical = CP.Props1SI("T_critical", self.refrigerant)  # Critical temperature (K)
            p_critical = CP.Props1SI("p_critical", self.refrigerant)  # Critical pressure (Pa)
            h_min = CP.PropsSI("H", "T", T_triple + 0.1, "Q", 0, self.refrigerant)
            T_max_K =  T_critical*0.9
            p_high = min(p_critical * 0.9, 30e5) 
            h_max = CP.PropsSI("H", "T", T_max_K, "P", p_high, self.refrigerant)
            self.nw_Heating_net._set_p_range([p_triple, p_high])
            self.nw_Heating_net._set_h_range([h_min,h_max])
            self.Heating_ude.params['dt'] = dt_DHN
            self.nw_Heating_net.solve('design')
    def interaction_simulation(self,dT_water):
        if self.mode=="COOLING_NET":
            self.net.heat_consumer.at[self.HC_heat_consumer_id, "qext_w"] =abs( self.Cooling_net_evaporator.Q.val)
            self.net.heat_consumer.at[self.HC_heat_consumer_id,"deltat_k"]=dT_water
            
        elif self.mode=="HEATING_NET":
            self.net.heat_consumer.at[self.HC_heat_consumer_id, "qext_w"] = self.Heating_net_condenser.Q.val
            self.net.heat_consumer.at[self.HC_heat_consumer_id,"deltat_k"]=dT_water

        else: 
            self.net.heat_consumer.at[self.HC_heat_consumer_id, "in_service"] =False
            self.net.heat_consumer.at[self.HC_heat_consumer_id, "in_service"] =False

    def get_main_results(self):
        if self.mode=="COOLING_NET":
            results = {
                "Q_consumer": abs(self.Cooling_net_condenser.Q.val),
                "Q_network": abs(self.Cooling_net_evaporator.Q.val),
                "W_compressor":self.Cooling_net_compressor.P.val ,
                "COP": abs(self.Cooling_net_condenser.Q.val)/self.Cooling_net_compressor.P.val 
            }
        elif self.mode=="HEATING_NET":
            results = {
                "Q_consumer": abs(self.Heating_net_evaporator.Q.val),
                "Q_network": abs(self.Heating_net_condenser.Q.val),
                "COP": abs(self.Heating_net_evaporator.Q.val)/self.Heating_net_compressor.P.val 
            }
        else:
            results = {}
        return results

    def get_results_solver(self):
        if self.mode=="COOLING_NET":
            self.nw_Cooling_net.print_results()
        elif self.mode=="HEATING_NET":
            self.nw_Heating_net.print_results()
        else:
            return None

In [97]:
net = pp.create_empty_network(fluid="water")
# Nudos de la Central / Fuente
j_fuente_ida = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Fuente_Ida")
j_nodo_1 = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="nodo_1_ida")
j_nodo_2=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="nodo_2_ida") 
j_HP_1 = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="HP_1_Ida")
j_HP_2 = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="HP_2_Ida")
#Return
j_fuente_ret = pp.create_junction(net, pn_bar=1.5, tfluid_k=333.15, name="Fuente_Retorno")
j_nodo_1_ret = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Node_1_ret")
j_nodo_2_ret=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo_2_ret") 
j_HP_ret_1= pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="HP_1_ret")
j_HP_ret_2=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="HP_2_ret")

#Plant-Nodo
u=0.35 / (np.pi * 0.15)
#Planta 1
pipe_ida_1 = pp.create_pipe_from_parameters(
    net, from_junction=j_fuente_ida, to_junction=j_nodo_1,
    length_km=0.0589, inner_diameter_mm=150, u_w_per_m2k=u, text_k=273.2, name="Tubo_Ida_Plant_Nodo_1",k_mm=0.1*1000
)

pipe_retorno_1= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_1_ret, to_junction=j_fuente_ret,
    length_km=0.0589, inner_diameter_mm=150, u_w_per_m2k=u,  text_k=273.2, name="Tubo_RetornoPlant_Nodo_1",k_mm=0.1*1000)

#Nodo-nodo
pipe_ida_2 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_1, to_junction=j_nodo_2,
    length_km=0.0589, inner_diameter_mm=150, u_w_per_m2k=u,  text_k=273.2, name="nodo_1_nodo_2",k_mm=0.1*1000
)
pipe_retorno_2= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_2_ret, to_junction=j_nodo_1_ret,
    length_km=0.0589, inner_diameter_mm=150, u_w_per_m2k=u,  text_k=273.2, name="nodo_2_ret_nodo_1_ret",k_mm=0.1*1000
)

#Node HP
#Node_Cons1

pipe_ida_3= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_2, to_junction=j_HP_1,
    length_km=0.0376, inner_diameter_mm=150, u_w_per_m2k=u,  text_k=273.2, name="Tubo_Ida_nodo_2_cons_1_ida",k_mm=0.1*1000
)
pipe_retorno_3= pp.create_pipe_from_parameters(
    net, from_junction=j_HP_ret_1, to_junction=j_nodo_2_ret,
    length_km=0.0376, inner_diameter_mm=150, u_w_per_m2k=u,  text_k=273.2, name="Tubo_Retorno_nodo_2_cons_1_ret",k_mm=0.1*1000
)
#Node_Cons2
pipe_ida_4 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_2, to_junction=j_HP_2,
    length_km=0.0302, inner_diameter_mm=150, u_w_per_m2k=u,  text_k=273.2, name="Tubo_Ida_nodo_2_cons_2_ida",k_mm=0.1*1000
)
pipe_retorno_4= pp.create_pipe_from_parameters(
    net, from_junction=j_HP_ret_2, to_junction=j_nodo_2_ret,
    length_km=0.0302, inner_diameter_mm=150, u_w_per_m2k=u,  text_k=273.2, name="Tubo_Retorno_nodo_2_cons_2_ret",k_mm=0.1*1000
)

#Heat Pumps
#Heat pump: extraction
HP_1=pp.create_heat_consumer(
    net,
    from_junction=j_HP_1 ,
    to_junction=j_HP_ret_1,
    qext_w=150000,
    deltat_k=50,
    name="HP_1_EXT"
)
#Heat pump: extraction
HP_2=pp.create_heat_consumer(
    net,
    from_junction=j_HP_2 ,
    to_junction=j_HP_ret_2,
    qext_w=150000,
    deltat_k=50,
    name="HP_2_EXT"
)
#Plant: 
Plant_1=pp.create_circ_pump_const_pressure(net,flow_junction=j_fuente_ida,return_junction=j_fuente_ret,p_flow_bar=3,plift_bar=0.5,t_flow_k=305 ,name='Grid')

In [98]:
T_network_inital_guess_1=35
T_network_inital_guess_2=60

In [ ]:
HP_1_object=Bidirectional_W_to_WHeatPump(name="heat_pump_1",refrigerant="R134a",net=net,HC_heat_consumer_id=HP_1)
HP_2_object=Bidirectional_W_to_WHeatPump(name="heat_pump_2",refrigerant="R134a",net=net,HC_heat_consumer_id=HP_2)

In [ ]:
T_network_HP_1=T_network_inital_guess_1
T_network_HP_2=T_network_inital_guess_2
T_network_HP_1_loop=T_network_inital_guess_1
T_network_HP_2_loop=T_network_inital_guess_2
tolerance=1E-6
error_1=10
error_2=10
iterations=0
while error_1>tolerance or error_2>tolerance:
    HP_1_object.solve_cycle(mode="COOLING_NET",Q_consumer=-15000,eta_s=0.95,T_nework_in=T_network_HP_1,T_cons=[50,60],dt_DHN=5)
    HP_2_object.solve_cycle(mode="HEATING_NET",Q_consumer=-150000,eta_s=0.95,T_nework_in=T_network_HP_2,T_cons=[35,25],dt_DHN=10)
    print("iteration")
    HP_1_object.interaction_simulation(dT_water=5)
    HP_2_object.interaction_simulation(dT_water=-10)
    pp.pipeflow(net=net,mode='bidirectional')
    T_network_HP_1=float(net.res_heat_consumer.at[HP_1_object.HC_heat_consumer_id,"t_from_k"]-273.15)
    T_network_HP_2=float(net.res_heat_consumer.at[HP_2_object.HC_heat_consumer_id,"t_from_k"]-273.15)
    error_1=abs(T_network_HP_1_loop-T_network_HP_1)
    error_2=abs(T_network_HP_2_loop-T_network_HP_2)
    print(error_1)
    print(error_2)
    T_network_HP_1_loop=T_network_HP_1
    T_network_HP_2_loop=T_network_HP_2
    iterations+=1

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 9.04e+05   | 0 %        | 1.74e+00   | 1.42e+06   | 4.03e+05   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 3.23e+04   | 16 %       | 9.74e-01   | 1.97e+05   | 6.96e+03   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 4.66e+03   | 25 %       | 2.22e-01   | 1.64e+04   | 4.58e+02   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 1.85e+00   | 63 %       | 1.18e-05   | 1.58e+02   | 4.33e+00   | 0.00e+00   | 0.00e+00   | 0.00e+00
 5     | 1.77e-04   | 100 %      | 8.99e-10   | 1.41e-02   | 3.71e-04   | 0.00e+00   | 0.00e+00   | 0.00e+00
 6     | 3.47e-10   | 100 %      | 5.48e-13   | 4.94e-09   | 1.90e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 6, Calculation time: 0.02 s, Iterations per second: 265.59

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 4.45e+06   | 0 %        | 2.77e+00   | 1.64e+06   | 3.63e+05   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 5.14e+05   | 3 %        | 1.41e+00   | 2.98e+06   | 2.09e+06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 2.11e+05   | 7 %        | 2.06e+02   | 5.14e+06   | 3.16e+05   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 5.49e+07   | 0 %        | 8.59e+02   | 9.96e+07   | 9.02e+05   | 0.00e+00   | 0.00e+00   | 0.00e+00
 5     | 3.57e+08   | 0 %        | 4.12e+03   | 1.86e+06   | 3.78e+05   | 0.00e+00   | 0.00e+00   | 0.00e+00
 6     | 1.99e+08   | 0 %        | 4.32e+03   | 4.04e+05   | 8.14e+03   | 0.00e+00   | 0.00e+00   | 0.00e+00
 7     | 1.03e+06   | 0 %        | 2.80e+01   | 5.97e+04   | 2.09e+03   | 0.00e+00   | 0.00e+00   | 0.00e+00
 8     | 2.11e+04   | 18 %       | 6.62e-01   | 2.70e+03   | 8.74e+01   | 0.00e+00   | 0.00e+00   | 0.00e+00
 9     | 1.85e+01   | 52 %       | 4.90e-04   | 4.85e+00   | 1.55e-01   | 0.00e+00   | 0.00e+00   | 0.00e+00
 10    | 4.02e-05   | 100 %      | 7.44e-10   | 1.56e-05   | 8.18e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 11    | 4.53e-10   | 100 %      | 1.38e-10   | 1.00e-09   | 1.23e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 11, Calculation time: 0.04 s, Iterations per second: 253.87
iteration
3.3744131056306514
28.226212825002563

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 8.51e+03   | 23 %       | 3.39e-02   | 6.69e+04   | 1.42e+04   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 4.70e+02   | 36 %       | 2.27e-02   | 2.49e+03   | 7.58e+01   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 6.87e-02   | 79 %       | 1.72e-06   | 3.92e+00   | 1.19e-01   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 1.19e-05   | 100 %      | 1.16e-12   | 9.69e-06   | 1.03e-05   | 0.00e+00   | 0.00e+00   | 0.00e+00
 5     | 6.23e-10   | 100 %      | 1.82e-11   | 1.04e-09   | 6.42e-07   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 5, Calculation time: 0.02 s, Iterations per second: 262.07

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 5.53e+05   | 2 %        | 7.85e-01   | 1.46e+06   | 1.29e+05   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 6.99e+04   | 12 %       | 5.06e-01   | 3.19e+04   | 4.78e+03   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 1.98e+03   | 30 %       | 9.52e-03   | 3.23e+02   | 3.99e+00   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 5.33e-02   | 80 %       | 4.26e-07   | 3.23e-02   | 4.00e-04   | 0.00e+00   | 0.00e+00   | 0.00e+00
 5     | 9.10e-10   | 100 %      | 2.52e-10   | 1.77e-09   | 2.64e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 6     | 4.95e-10   | 100 %      | 3.61e-12   | 0.00e+00   | 3.78e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 6, Calculation time: 0.02 s, Iterations per second: 253.13
iteration
0.012188133308598026
0.012135074928210088

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 3.02e+01   | 50 %       | 4.09e-05   | 2.24e+02   | 5.14e+01   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 2.02e-03   | 96 %       | 9.77e-08   | 3.15e-02   | 9.48e-04   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 5.99e-10   | 100 %      | 1.66e-11   | 2.59e-06   | 5.75e-07   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 4.73e-10   | 100 %      | 1.66e-11   | 2.60e-06   | 5.76e-07   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.01 s, Iterations per second: 293.30

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 2.03e+02   | 41 %       | 2.53e-04   | 3.78e+02   | 5.45e+01   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 1.30e-02   | 87 %       | 2.46e-07   | 4.42e-02   | 5.47e-04   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 1.56e-09   | 100 %      | 2.57e-10   | 1.77e-09   | 2.68e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 1.04e-09   | 100 %      | 2.58e-10   | 1.77e-09   | 2.70e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.01 s, Iterations per second: 270.50
iteration
1.5303588895676512e-05
4.9585909209781676e-06

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 3.79e-02   | 82 %       | 5.13e-08   | 2.81e-01   | 6.46e-02   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 1.18e-05   | 100 %      | 7.88e-13   | 1.24e-07   | 1.06e-05   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 4.99e-10   | 100 %      | 6.21e-13   | 7.51e-08   | 2.25e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 3.66e-10   | 100 %      | 1.69e-11   | 4.65e-22   | 5.97e-07   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.02 s, Iterations per second: 252.65

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 8.28e-02   | 78 %       | 1.03e-07   | 1.54e-01   | 2.23e-02   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 1.26e-05   | 100 %      | 1.67e-11   | 1.98e-05   | 8.73e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 2.53e-10   | 100 %      | 2.98e-12   | 0.00e+00   | 3.11e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 9.19e-10   | 100 %      | 2.53e-10   | 0.00e+00   | 2.64e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.02 s, Iterations per second: 264.45
iteration
1.647100589252659e-08
2.53470489042229e-09

In [101]:
net.heat_consumer

,name,from_junction,to_junction,qext_w,controlled_mdot_kg_per_s,deltat_k,treturn_k,in_service,type
0,HP_1_EXT,3,8,12372.271294,NaN,5.0,NaN,True,heat_consumer
1,HP_2_EXT,4,9,-167063.796762,NaN,-10.0,NaN,True,heat_consumer

In [102]:
net.res_heat_consumer

,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s,deltat_k,qext_w
0,2.879312,2.620972,304.763383,299.763383,299.763383,0.591898,-0.591898,0.000594,5.0,12372.271294
1,2.856605,2.643749,304.911647,314.911647,314.911647,3.996757,-3.996757,0.004024,-10.0,-167063.796762

In [103]:
net.heat_consumer

,name,from_junction,to_junction,qext_w,controlled_mdot_kg_per_s,deltat_k,treturn_k,in_service,type
0,HP_1_EXT,3,8,12372.271294,NaN,5.0,NaN,True,heat_consumer
1,HP_2_EXT,4,9,-167063.796762,NaN,-10.0,NaN,True,heat_consumer

In [104]:
net.res_heat_consumer

,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s,deltat_k,qext_w
0,2.879312,2.620972,304.763383,299.763383,299.763383,0.591898,-0.591898,0.000594,5.0,12372.271294
1,2.856605,2.643749,304.911647,314.911647,314.911647,3.996757,-3.996757,0.004024,-10.0,-167063.796762

In [105]:
net.circ_pump_pressure

,name,return_junction,flow_junction,p_flow_bar,t_flow_k,plift_bar,in_service,type
0,Grid,5,0,3.0,305.0,0.5,True,pt

In [106]:
net.res_circ_pump_pressure

,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s,deltat_k,qext_w
0,2.5,3.0,312.831095,305.0,305.0,4.588655,-4.588655,0.004618,7.831095,-150197.889654

In [107]:
net.ext_grid

Empty DataFrame
Columns: [name, junction, p_bar, t_k, in_service, type]
Index: []

In [108]:
net.res_ext_grid

Empty DataFrame
Columns: [mdot_kg_per_s]
Index: []

In [109]:
net.res_junction

      p_bar         t_k
0  3.000000  305.000000
1  2.939980  304.965840
2  2.879961  304.931717
3  2.879312  304.763383
4  2.856605  304.911647
5  2.500000  312.831095
6  2.560161  312.873717
7  2.620322  312.916384
8  2.620972  299.763383
9  2.643749  314.911647

In [110]:
net.pipe

,name,from_junction,to_junction,std_type,length_km,inner_diameter_mm,outer_diameter_mm,k_mm,loss_coefficient,u_w_per_m2k,text_k,sections,in_service,type
0,Tubo_Ida_Plant_Nodo_1,0,1,None,0.0589,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
1,Tubo_RetornoPlant_Nodo_1,6,5,None,0.0589,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
2,nodo_1_nodo_2,1,2,None,0.0589,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
3,nodo_2_ret_nodo_1_ret,7,6,None,0.0589,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
4,Tubo_Ida_nodo_2_cons_1_ida,2,3,None,0.0376,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
5,Tubo_Retorno_nodo_2_cons_1_ret,8,7,None,0.0376,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
6,Tubo_Ida_nodo_2_cons_2_ida,2,4,None,0.0302,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
7,Tubo_Retorno_nodo_2_cons_2_ret,9,7,None,0.0302,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe

In [111]:
net.res_pipe

,v_mean_m_per_s,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s,reynolds,lambda,dp_friction_loss_bar
0,0.260968,3.000000,2.939980,305.000000,304.965840,304.965840,4.588655,-4.588655,0.004612,50777.496622,0.451129,0.060020
1,0.261687,2.560161,2.500000,312.873717,312.831095,312.831095,4.588655,-4.588655,0.004624,59467.230817,0.450944,0.060161
2,0.260965,2.939980,2.879961,304.965840,304.931717,304.931717,4.588655,-4.588655,0.004612,50742.264131,0.451129,0.060019
3,0.261691,2.620322,2.560161,312.916384,312.873717,312.873717,4.588655,-4.588655,0.004624,59519.158692,0.450943,0.060161
4,0.033661,2.879961,2.879312,304.931717,304.763383,304.763383,0.591898,-0.591898,0.000595,6531.888833,0.459666,0.000650
5,0.033610,2.620972,2.620322,299.763383,312.916384,299.622504,0.591898,-0.591898,0.000594,5849.901083,0.460809,0.000650
6,0.227300,2.879961,2.856605,304.931717,304.911647,304.911647,3.996757,-3.996757,0.004017,44172.612174,0.451317,0.023356
7,0.228119,2.643749,2.620322,314.911647,312.916384,314.885265,3.996757,-3.996757,0.004031,53734.250065,0.451059,0.023427

In [112]:
results_1=HP_1.get_main_results()
results_2=HP_2.get_main_results()

In [113]:
print(results_1)

{'Q_consumer': 15000.0, 'Q_network': 12372.27129388467, 'W_compressor': 2627.728706115295, 'COP': 5.708351842064877}

In [114]:
15000.0/1685.6799401256844

8.898486386971895

In [115]:
print(results_2)

{'Q_consumer': 150000.0, 'Q_network': 167063.7967616218, 'COP': 8.790540704127768}

In [116]:
HP_1.get_results_solver()

##### RESULTS (CycleCloser) #####
+-------------+------------------+-------------------+
|             |   mass_deviation |   fluid_deviation |
|-------------+------------------+-------------------|
| CycleCloser |         0.00e+00 |          0.00e+00 |
+-------------+------------------+-------------------+
##### RESULTS (Compressor) #####
+-----------+----------+----------+-----------+----------+
|           |        P |       pr |        dp |    eta_s |
|-----------+----------+----------+-----------+----------|
| compresor | 2.63e+03 | 3.15e+00 | -1.29e+01 | 9.50e-01 |
+-----------+----------+----------+-----------+----------+
##### RESULTS (Condenser) #####
+-------------+-----------+----------+----------+----------+----------+----------+----------+-----------+----------+----------+----------+----------+------------+----------+------------+----------+-----------+------------+-----------+
|             |         Q |       UA |       kA |   td_log |     lmtd |    ttd_u |    ttd_l |   ttd_min |      pr1 |      pr2 |      dp1 |      dp2 |   zeta1_d4 |    zeta1 |   zeta2_d4 |    zeta2 |   eff_hot |   eff_cold |   eff_max |
|-------------+-----------+----------+----------+----------+----------+----------+----------+-----------+----------+----------+----------+----------+------------+----------+------------+----------+-----------+------------+-----------|
| condensador | -1.50e+04 | 1.65e+03 | 1.65e+03 | 9.10e+00 | 9.10e+00 | 5.00e+00 | 1.50e+01 |  5.00e+00 | 1.00e+00 | 1.00e+00 | 0.00e+00 | 0.00e+00 |   0.00e+00 | 0.00e+00 |   0.00e+00 | 0.00e+00 |  8.56e-01 |   4.06e-01 |  8.56e-01 |
+-------------+-----------+----------+----------+----------+----------+----------+----------+-----------+----------+----------+----------+----------+------------+----------+------------+----------+-----------+------------+-----------+
##### RESULTS (HeatExchanger) #####
+------------+-----------+----------+----------+----------+----------+----------+----------+-----------+----------+----------+----------+----------+------------+----------+------------+----------+-----------+------------+-----------+
|            |         Q |       UA |       kA |   td_log |     lmtd |    ttd_u |    ttd_l |   ttd_min |      pr1 |      pr2 |      dp1 |      dp2 |   zeta1_d4 |    zeta1 |   zeta2_d4 |    zeta2 |   eff_hot |   eff_cold |   eff_max |
|------------+-----------+----------+----------+----------+----------+----------+----------+-----------+----------+----------+----------+----------+------------+----------+------------+----------+-----------+------------+-----------|
| evaporador | -1.24e+04 | 2.47e+03 | 2.47e+03 | 5.00e+00 | 5.00e+00 | 5.00e+00 | 5.00e+00 |  5.00e+00 | 1.00e+00 | 1.00e+00 | 0.00e+00 | 0.00e+00 |   0.00e+00 | 0.00e+00 |   0.00e+00 | 0.00e+00 |  5.00e-01 |   9.60e-01 |  9.60e-01 |
+------------+-----------+----------+----------+----------+----------+----------+----------+-----------+----------+----------+----------+----------+------------+----------+------------+----------+-----------+------------+-----------+
##### RESULTS (Valve) #####
+-------------------+----------+----------+-----------+----------+
|                   |       pr |       dp |   zeta_d4 |     zeta |
|-------------------+----------+----------+-----------+----------|
| valvula_expansion | 3.18e-01 | 1.29e+01 |  2.13e+10 | 2.13e+10 |
+-------------------+----------+----------+-----------+----------+
##### RESULTS (Connection) #####
+----+-----------+-----------+-----------+-----------+-----------+---------+
|    |         m |         p |         h |         T |         x | phase   |
|----+-----------+-----------+-----------+-----------+-----------+---------|
|  0 | 1.032e-01 | 6.008e+00 | 2.958e+05 | 2.161e+01 | 3.651e-01 | tp      |
|  1 | 1.032e-01 | 6.008e+00 | 2.958e+05 | 2.161e+01 | 3.651e-01 | tp      |
|  2 | 1.032e-01 | 6.008e+00 | 4.156e+05 | 2.661e+01 | 1.000e+00 | g       |
|  3 | 1.032e-01 | 1.890e+01 | 4.410e+05 | 7.458e+01 | 1.000e+00 | g       |
|  4 | 1.032e-01 | 1.890e+01 | 2.958e+05 | 6.500e+01 | 1.620e-15 | tp      |
|  5 | 3.586e-01 | 3.000e+00 | 2.514e+05 | 6.000e+01 | 0.000e+00 | l       |
|  6 | 3.586e-01 | 3.000e+00 | 2.096e+05 | 5.000e+01 | 0.000e+00 | l       |
|  7 | 5.920e-01 | 2.500e+00 | 1.327e+05 | 3.161e+01 | 0.000e+00 | l       |
|  8 | 5.920e-01 | 2.500e+00 | 1.118e+05 | 2.661e+01 | 0.000e+00 | l       |
+----+-----------+-----------+-----------+-----------+-----------+---------+

In [117]:
HP_2.get_results_solver()

##### RESULTS (CycleCloser) #####
+-------------+------------------+-------------------+
|             |   mass_deviation |   fluid_deviation |
|-------------+------------------+-------------------|
| CycleCloser |         0.00e+00 |          0.00e+00 |
+-------------+------------------+-------------------+
##### RESULTS (Compressor) #####
+-----------+----------+----------+-----------+----------+
|           |        P |       pr |        dp |    eta_s |
|-----------+----------+----------+-----------+----------|
| compresor | 1.71e+04 | 2.12e+00 | -6.42e+00 | 9.50e-01 |
+-----------+----------+----------+-----------+----------+
##### RESULTS (Condenser) #####
+-------------+-----------+----------+----------+----------+----------+----------+----------+-----------+----------+----------+----------+----------+------------+----------+------------+----------+-----------+------------+-----------+
|             |         Q |       UA |       kA |   td_log |     lmtd |    ttd_u |    ttd_l |   ttd_min |      pr1 |      pr2 |      dp1 |      dp2 |   zeta1_d4 |    zeta1 |   zeta2_d4 |    zeta2 |   eff_hot |   eff_cold |   eff_max |
|-------------+-----------+----------+----------+----------+----------+----------+----------+-----------+----------+----------+----------+----------+------------+----------+------------+----------+-----------+------------+-----------|
| condensador | -1.67e+05 | 1.84e+04 | 1.84e+04 | 9.10e+00 | 9.10e+00 | 5.00e+00 | 1.50e+01 |  5.00e+00 | 1.00e+00 | 1.00e+00 | 0.00e+00 | 0.00e+00 |   0.00e+00 | 0.00e+00 |   0.00e+00 | 0.00e+00 |  8.81e-01 |   4.35e-01 |  8.81e-01 |
+-------------+-----------+----------+----------+----------+----------+----------+----------+-----------+----------+----------+----------+----------+------------+----------+------------+----------+-----------+------------+-----------+
##### RESULTS (HeatExchanger) #####
+------------+-----------+----------+----------+----------+----------+----------+----------+-----------+----------+----------+----------+----------+------------+----------+------------+----------+-----------+------------+-----------+
|            |         Q |       UA |       kA |   td_log |     lmtd |    ttd_u |    ttd_l |   ttd_min |      pr1 |      pr2 |      dp1 |      dp2 |   zeta1_d4 |    zeta1 |   zeta2_d4 |    zeta2 |   eff_hot |   eff_cold |   eff_max |
|------------+-----------+----------+----------+----------+----------+----------+----------+-----------+----------+----------+----------+----------+------------+----------+------------+----------+-----------+------------+-----------|
| evaporador | -1.50e+05 | 2.08e+04 | 2.08e+04 | 7.21e+00 | 7.21e+00 | 1.00e+01 | 5.00e+00 |  5.00e+00 | 1.00e+00 | 1.00e+00 | 0.00e+00 | 0.00e+00 |   0.00e+00 | 0.00e+00 |   0.00e+00 | 0.00e+00 |  6.67e-01 |   9.38e-01 |  9.38e-01 |
+------------+-----------+----------+----------+----------+----------+----------+----------+-----------+----------+----------+----------+----------+------------+----------+------------+----------+-----------+------------+-----------+
##### RESULTS (Valve) #####
+-------------------+----------+----------+-----------+----------+
|                   |       pr |       dp |   zeta_d4 |     zeta |
|-------------------+----------+----------+-----------+----------|
| valvula_expansion | 4.71e-01 | 6.42e+00 |  1.67e+08 | 1.67e+08 |
+-------------------+----------+----------+-----------+----------+
##### RESULTS (Connection) #####
+----+-----------+-----------+-----------+-----------+-----------+---------+
|    |         m |         p |         h |         T |         x | phase   |
|----+-----------+-----------+-----------+-----------+-----------+---------|
|  0 | 1.013e+00 | 5.717e+00 | 2.666e+05 | 2.000e+01 | 2.149e-01 | tp      |
|  1 | 1.013e+00 | 5.717e+00 | 2.666e+05 | 2.000e+01 | 2.149e-01 | tp      |
|  2 | 1.013e+00 | 5.717e+00 | 4.147e+05 | 2.500e+01 | 1.000e+00 | g       |
|  3 | 1.013e+00 | 1.214e+01 | 4.316e+05 | 5.472e+01 | 1.000e+00 | g       |
|  4 | 1.013e+00 | 1.214e+01 | 2.666e+05 | 4.676e+01 | 0.000e+00 | tp      |
|  5 | 3.589e+00 | 3.000e+00 | 1.051e+05 | 2.500e+01 | 0.000e+00 | l       |
|  6 | 3.589e+00 | 3.000e+00 | 1.469e+05 | 3.500e+01 | 0.000e+00 | l       |
|  7 | 3.998e+00 | 2.500e+00 | 1.333e+05 | 3.176e+01 | 0.000e+00 | l       |
|  8 | 3.998e+00 | 2.500e+00 | 1.751e+05 | 4.176e+01 | 0.000e+00 | l       |
+----+-----------+-----------+-----------+-----------+-----------+---------+