In [1]:
import numpy as np
import pandapipes as pp

# 1. Crear red vacía
net = pp.create_empty_network(fluid="water")

# =============================================================================
# NUDOS (JUNCTIONS)
# =============================================================================
# Nota: Las temperaturas en pandapipes se introducen en Kelvin (K = °C + 273.15)
# Suponemos Ida a 80 °C (353.15 K) y Retorno esperado a 60 °C (333.15 K)


j_fuente_ida = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Fuente_Ida")
j_cons_ida = pp.create_junction(net, pn_bar=4.8, tfluid_k=353.15, name="Consumidor1_Ida")
j_cons_ida_2 = pp.create_junction(net, pn_bar=4.8, tfluid_k=353.15, name="Consumidor2_Ida")
j_cons_ida_3 = pp.create_junction(net, pn_bar=4.8, tfluid_k=353.15, name="Consumidor3_Ida")
j_cons_ida_4 = pp.create_junction(net, pn_bar=4.8, tfluid_k=353.15, name="Consumidor4_Ida")
j_fuente_ret = pp.create_junction(net, pn_bar=1.5, tfluid_k=333.15, name="Fuente_Retorno")
j_cons_ret = pp.create_junction(net, pn_bar=1.7, tfluid_k=333.15, name="Consumidor1_Retorno")
j_cons_ret_2 = pp.create_junction(net, pn_bar=1.7, tfluid_k=333.15, name="Consumidor2_Retorno")
j_cons_ret_3 = pp.create_junction(net, pn_bar=1.7, tfluid_k=333.15, name="Consumidor3_Retorno")
j_cons_ret_4 = pp.create_junction(net, pn_bar=1.7, tfluid_k=333.15, name="Consumidor4_Retorno")


# =============================================================================
# TUBERÍAS (PIPES) - IDA Y RETORNO SIN PÉRDIDAS TÉRMICAS (k_w = 0)
# =============================================================================

pipe_ida_1 = pp.create_pipe_from_parameters(
    net, from_junction=j_fuente_ida, to_junction=j_cons_ida,
    length_km=0.0155, inner_diameter_mm=150, u_w_per_m2k=0, k_mm=0.1*1000, text_k=273.2, name="Tubo_Ida_Plant_Consm_1",
)

pipe_retorno_1= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret, to_junction=j_fuente_ret,
    length_km=0.0155, inner_diameter_mm=150, u_w_per_m2k=0, k_mm=0.1*1000, text_k=273.2, name="Tubo_RetornoPlant_Consm_1",
)

pipe_ida_2 = pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ida, to_junction=j_cons_ida_2,
    length_km=0.0154, inner_diameter_mm=150, u_w_per_m2k=0, k_mm=0.1*1000, text_k=273.2, name="Tubo_Ida_Consm1_Consm_2",
)
pipe_retorno_2= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret_2, to_junction=j_cons_ret,
    length_km=0.0154, inner_diameter_mm=150, u_w_per_m2k=0, k_mm=0.1*1000, text_k=273.2, name="Tubo_Retorno_Consm1_Consm_2",  
)
pipe_ida_3 = pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ida_2, to_junction=j_cons_ida_3,
    length_km=0.0139, inner_diameter_mm=150, u_w_per_m2k=0, k_mm=0.1*1000, text_k=273.2, name="Tubo_Ida_Consm2_Consm_3",
)

pipe_retorno_3= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret_3, to_junction=j_cons_ret_2,
    length_km=0.0139, inner_diameter_mm=150, u_w_per_m2k=0, k_mm=0.1*1000, text_k=273.2, name="Tubo_Retorno_Consm2_Consm_3",
)
pipe_ida_4 = pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ida_3, to_junction=j_cons_ida_4,
    length_km=0.0176, inner_diameter_mm=150, u_w_per_m2k=0, k_mm=0.1*1000, text_k=273.2, name="Tubo_Ida_Consm3_Consm_4",
)

pipe_retorno_4= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret_4, to_junction=j_cons_ret_3,
    length_km=0.0176, inner_diameter_mm=150, u_w_per_m2k=0, k_mm=0.1*1000, text_k=273.2, name="Tubo_Retorno_Consm3_Consm_4",
)
pipe_ida_5= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ida_4, to_junction=j_fuente_ida,
    length_km=0.0128, inner_diameter_mm=150, u_w_per_m2k=0, k_mm=0.1*1000, text_k=273.2, name="Tubo_ida_Consm4_plant",
)
pipe_retorno_5= pp.create_pipe_from_parameters(
    net, from_junction=j_fuente_ret, to_junction=j_cons_ret_4,
    length_km=0.0128, inner_diameter_mm=150, u_w_per_m2k=0, k_mm=0.1*1000, text_k=273.2, name="Tubo_Retorno_Consm4_plant",
)
# =============================================================================
# COMPONENTE CONSUMIDOR (Potencia en W y Temp de Retorno)
# =============================================================================
# Conectamos el nudo de ida con el de retorno. 
# El sistema extraerá agua de la ida, absorberá los Watts indicados y la devolverá al retorno a la t_return_k.

pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida,
    to_junction=j_cons_ret,
    qext_w=300000,
    treturn_k=313.2,
    name="Consumidor_1"
)
pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida_2,
    to_junction=j_cons_ret_2,
    qext_w=300000,
    treturn_k=313.2,
    name="Consumidor_2"
)
pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida_3,
    to_junction=j_cons_ret_3,
    qext_w=300000,
    treturn_k=313.2,
    name="Consumidor_3"
)
pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida_4,
    to_junction=j_cons_ret_4,
    qext_w=300000,
    treturn_k=313.2,
    name="Consumidor_4"
)

# =============================================================================
# CONDICIONES DE CONTORNO (EXT_GRID)
# =============================================================================
# Fijamos la presión y temperatura de salida en la ida

pp.create_circ_pump_const_pressure(net,flow_junction=j_fuente_ida,return_junction=j_fuente_ret,p_flow_bar=3,plift_bar=0.5,t_flow_k=353 ,name='Grid'
)


# =============================================================================
# SIMULACIÓN Y RESULTADOS
# =============================================================================
pp.pipeflow(net, mode="bidirectional")

In [2]:
net.res_circ_pump_pressure

,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s,deltat_k,qext_w
0,2.5,3.0,313.2,353.0,353.0,7.198858,-7.198858,0.007331,-39.8,1200000.0

In [3]:
net.pipe

,name,from_junction,to_junction,std_type,length_km,inner_diameter_mm,outer_diameter_mm,k_mm,loss_coefficient,u_w_per_m2k,text_k,sections,in_service,type
0,Tubo_Ida_Plant_Consm_1,0,1,None,0.0155,150.0,150.0,100.0,0.0,0.0,273.2,1,True,pipe
1,Tubo_RetornoPlant_Consm_1,6,5,None,0.0155,150.0,150.0,100.0,0.0,0.0,273.2,1,True,pipe
2,Tubo_Ida_Consm1_Consm_2,1,2,None,0.0154,150.0,150.0,100.0,0.0,0.0,273.2,1,True,pipe
3,Tubo_Retorno_Consm1_Consm_2,7,6,None,0.0154,150.0,150.0,100.0,0.0,0.0,273.2,1,True,pipe
4,Tubo_Ida_Consm2_Consm_3,2,3,None,0.0139,150.0,150.0,100.0,0.0,0.0,273.2,1,True,pipe
5,Tubo_Retorno_Consm2_Consm_3,8,7,None,0.0139,150.0,150.0,100.0,0.0,0.0,273.2,1,True,pipe
6,Tubo_Ida_Consm3_Consm_4,3,4,None,0.0176,150.0,150.0,100.0,0.0,0.0,273.2,1,True,pipe
7,Tubo_Retorno_Consm3_Consm_4,9,8,None,0.0176,150.0,150.0,100.0,0.0,0.0,273.2,1,True,pipe
8,Tubo_ida_Consm4_plant,4,0,None,0.0128,150.0,150.0,100.0,0.0,0.0,273.2,1,True,pipe
9,Tubo_Retorno_Consm4_plant,5,9,None,0.0128,150.0,150.0,100.0,0.0,0.0,273.2,1,True,pipe

In [4]:
net.res_pipe

,v_mean_m_per_s,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s,reynolds,lambda,dp_friction_loss_bar
0,0.204588,3.000000,2.990530,353.0,353.0,353.0,3.513380,-3.513380,0.003615,84244.326919,0.450628,0.009470
1,0.200392,2.509289,2.500000,313.2,313.2,313.2,3.513390,-3.513390,0.003541,45830.134573,0.451265,0.009289
2,0.099789,2.990530,2.988287,353.0,353.0,353.0,1.713665,-1.713665,0.001763,41090.510186,0.451426,0.002242
3,0.097743,2.511492,2.509289,313.2,313.2,313.2,1.713676,-1.713676,0.001727,22353.906513,0.452731,0.002203
4,-0.005011,2.988287,2.988293,353.0,353.0,353.0,-0.086049,0.086049,-0.000089,2063.306547,0.480886,-0.000005
5,-0.004907,2.511486,2.511492,313.2,313.2,313.2,-0.086039,0.086039,-0.000087,1122.321547,0.506893,-0.000006
6,-0.109810,2.988293,2.991395,353.0,353.0,353.0,-1.885764,1.885764,-0.001941,45217.123280,0.451284,-0.003102
7,-0.107557,2.508440,2.511486,313.2,313.2,313.2,-1.885753,1.885753,-0.001901,24598.549607,0.452470,-0.003047
8,-0.214610,2.991395,3.000000,353.0,353.0,353.0,-3.685478,3.685478,-0.003792,88370.940012,0.450592,-0.008605
9,-0.210207,2.500000,2.508440,313.2,313.2,313.2,-3.685468,3.685468,-0.003715,48074.777668,0.451199,-0.008440