In [21]:
# import numpy as np
import numpy as np
import pandapipes as pp
from pandapipes.pf.pipeflow_setup import get_fluid
# 1. Crear red vacía
net = pp.create_empty_network(fluid="water")

# =============================================================================
# NUDOS (JUNCTIONS)
# =============================================================================
# Nota: Las temperaturas en pandapipes se introducen en Kelvin (K = °C + 273.15)
# Ida 
j_fuente_ida = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Fuente_Ida")
j_fuente_2_ida = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Fuente_2_Ida")
j_fuente_3_ida = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Fuente_3_Ida")
j_nodo_1=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo1_ida")
j_nodo_2=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo2_ida")
j_nodo_3=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo3_ida")
j_nodo_4=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo4_ida")
j_nodo_5=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo5_ida")
j_nodo_6=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo6_ida")
j_cons_ida_1 = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Consumidor1_Ida")
j_cons_ida_2 = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Consumidor2_Ida")
j_cons_ida_3 = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Consumidor3_Ida")
j_cons_ida_4 = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Consumidor4_Ida")
j_cons_ida_5 = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Consumidor5_Ida")
j_cons_ida_6 = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Consumidor6_Ida")
j_cons_ida_7 = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Consumidor7_Ida")
j_cons_ida_8 = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Consumidor8_Ida")
j_cons_ida_9 = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Consumidor9_Ida")
#Retorno 
j_fuente_ret = pp.create_junction(net, pn_bar=5.0, tfluid_k=305, name="Fuente_Retorno")
j_fuente_2_ret = pp.create_junction(net, pn_bar=5.0, tfluid_k=305, name="Fuente_2_Retorno")
j_fuente_3_ret = pp.create_junction(net, pn_bar=5.0, tfluid_k=305, name="Fuente_3_Retorno")
j_nodo_1_ret=pp.create_junction(net, pn_bar=5.0, tfluid_k=305, name="Nodo1_ret")
j_nodo_2_ret=pp.create_junction(net, pn_bar=5.0, tfluid_k=305, name="Nodo2_ret")
j_nodo_3_ret=pp.create_junction(net, pn_bar=5.0, tfluid_k=305, name="Nodo3_ret")
j_nodo_4_ret=pp.create_junction(net, pn_bar=5.0, tfluid_k=305, name="Nodo4_ret")
j_nodo_5_ret=pp.create_junction(net, pn_bar=5.0, tfluid_k=305, name="Nodo5_ret")
j_nodo_6_ret=pp.create_junction(net, pn_bar=5.0, tfluid_k=305, name="Nodo6_ret")
j_cons_ret_1 = pp.create_junction(net, pn_bar=5.0, tfluid_k=305, name="Consumidor1_Retorno")
j_cons_ret_2 = pp.create_junction(net, pn_bar=5.0, tfluid_k=305, name="Consumidor2_Retorno")
j_cons_ret_3 = pp.create_junction(net, pn_bar=5.0, tfluid_k=305, name="Consumidor3_Retorno")
j_cons_ret_4 = pp.create_junction(net, pn_bar=5.0, tfluid_k=305, name="Consumidor4_Retorno")
j_cons_ret_5 = pp.create_junction(net, pn_bar=5.0, tfluid_k=305, name="Consumidor5_Retorno")
j_cons_ret_6 = pp.create_junction(net, pn_bar=5.0, tfluid_k=305, name="Consumidor6_Retorno")
j_cons_ret_7 = pp.create_junction(net, pn_bar=5.0, tfluid_k=305, name="Consumidor7_Retorno")
j_cons_ret_8 = pp.create_junction(net, pn_bar=5.0, tfluid_k=305, name="Consumidor8_Retorno")
j_cons_ret_9 = pp.create_junction(net, pn_bar=5.0, tfluid_k=305, name="Consumidor9_Retorno")
#Inter
j_fuente_2_inter= pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Fuente_2_inter")
j_fuente_3_inter= pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Fuente_3_inter")

In [22]:
# =============================================================================
# TUBERÍAS (PIPES) - IDA Y RETORNO SIN PÉRDIDAS TÉRMICAS (k_w = 0)
# =============================================================================

#Plant-Nodo
#Planta 1
pipe_ida_1 = pp.create_pipe_from_parameters(
    net, from_junction=j_fuente_ida, to_junction=j_nodo_1,
    length_km=0.0374, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15), text_k=273.2, name="Tubo_Ida_Plant_nodo_1",k_mm=0.1
)

pipe_retorno_1= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_1_ret, to_junction=j_fuente_ret,
    length_km=0.0374, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_RetornoPlant_nodo_1",k_mm=0.1
)
#Planta 2
pipe_ida_2 = pp.create_pipe_from_parameters(
    net, from_junction=j_fuente_2_ida, to_junction=j_nodo_3,
    length_km=0.0265, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_Plant_2_nodo_3",k_mm=0.1
)

pipe_retorno_2= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_3_ret, to_junction=j_fuente_2_ret,
    length_km=0.0265, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_RetornoPlant_2_nodo_3",k_mm=0.1
)
#Planta 3
pipe_ida_3 = pp.create_pipe_from_parameters(
    net, from_junction=j_fuente_3_ida, to_junction=j_nodo_6,
    length_km=0.0624, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),text_k=273.2, name="Tubo_Ida_Plant_3_nodo_6",k_mm=0.1)

pipe_retorno_3= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_6_ret, to_junction=j_fuente_3_ret,
    length_km=0.0624, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_RetornoPlant_3_nodo_6",k_mm=0.1
)
#Nodo-nodo
#1-2
pipe_ida_4 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_1, to_junction=j_nodo_2,
    length_km=0.0254, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_nodo_1_nodo_2",k_mm=0.1
)
pipe_retorno_4= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_2_ret, to_junction=j_nodo_1_ret,
    length_km=0.0254, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Retorno_nodo_1_nodo_2",k_mm=0.1
    
)
#1-3
pipe_ida_5 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_1, to_junction=j_nodo_3,
    length_km=0.0316, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_nodo_1_nodo_3",k_mm=0.1
)
pipe_retorno_5= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_3_ret, to_junction=j_nodo_1_ret,
   length_km=0.0316, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Retorno_nodo_1_nodo_3",k_mm=0.1  
)
#3-4
pipe_ida_6 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_3, to_junction=j_nodo_4,
    length_km=0.0498, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_nodo_3_nodo_4",k_mm=0.1
)
pipe_retorno_6= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_4_ret, to_junction=j_nodo_3_ret,
    length_km=0.0498, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Retorno_nodo_3_nodo_4",k_mm=0.1   
)
#4-5
pipe_ida_7 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_4, to_junction=j_nodo_5,
    length_km=0.0349, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_nodo_4_nodo_5",k_mm=0.1
)
pipe_retorno_7= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_5_ret, to_junction=j_nodo_4_ret,
    length_km=0.0349, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Retorno_nodo_4_nodo_5",k_mm=0.1   
)
#5-6
pipe_ida_8 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_5, to_junction=j_nodo_6,
    length_km=0.043, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_nodo_5_nodo_6",k_mm=0.1
)
pipe_retorno_8= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_6_ret, to_junction=j_nodo_5_ret,
    length_km=0.043, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Retorno_nodo_5_nodo_6",k_mm=0.1   
)
#Nodo 2
#Consumer1
pipe_ida_9 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_2, to_junction=j_cons_ida_1,
    length_km=0.0155, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_nodo_2_consm_1",k_mm=0.1
)
pipe_retorno_9= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret_1, to_junction=j_nodo_2_ret,
    length_km=0.0155, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Retorno_nodo_2_consm_1",k_mm=0.1  
)
#Consumer2
pipe_ida_10 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_2, to_junction=j_cons_ida_2,
    length_km=0.0122, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_nodo_2_consm_2",k_mm=0.1
)
pipe_retorno_10= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret_2, to_junction=j_nodo_2_ret,
    length_km=0.0122, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Retorno_nodo_2_consm_2",k_mm=0.1  
)
#Consumer3
pipe_ida_11 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_2, to_junction=j_cons_ida_3,
    length_km=0.0161, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_nodo_2_consm_3",k_mm=0.1
)
pipe_retorno_11= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret_3, to_junction=j_nodo_2_ret,
    length_km=0.0161, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Retorno_nodo_2_consm_3",k_mm=0.1 
)
#Nodo 4
#Consumer4
pipe_ida_12 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_4, to_junction=j_cons_ida_4,
    length_km=0.016, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_nodo_4_consm_4",k_mm=0.1
)
pipe_retorno_12= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret_4, to_junction=j_nodo_4_ret,
    length_km=0.016, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Retorno_nodo_4_consm_4",k_mm=0.1
)
#Consumer5
pipe_ida_13 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_4, to_junction=j_cons_ida_5,
    length_km=0.0158, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_nodo_4_consm_5",k_mm=0.1
)
pipe_retorno_13= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret_5, to_junction=j_nodo_4_ret,
    length_km=0.0158, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Retorno_nodo_4_consm_5",k_mm=0.1   
)
#Consumer6
pipe_ida_14 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_4, to_junction=j_cons_ida_6,
    length_km=0.0176, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_nodo_4_consm_6",k_mm=0.1
)
pipe_retorno_14= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret_6, to_junction=j_nodo_4_ret,
    length_km=0.0176, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Retorno_nodo_4_consm_6",k_mm=0.1  
)
#Nodo 6
#Consumer7
pipe_ida_15 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_6, to_junction=j_cons_ida_7,
    length_km=0.0336, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_nodo_6_consm_7",k_mm=0.1
)
pipe_retorno_15= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret_7, to_junction=j_nodo_6_ret,
    length_km=0.0336, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Retorno_nodo_6_consm_7",k_mm=0.1 
)
#Consumer8
pipe_ida_16 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_6, to_junction=j_cons_ida_8,
    length_km=0.0422, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_nodo_6_consm_8",k_mm=0.1
)
pipe_retorno_16= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret_8, to_junction=j_nodo_6_ret,
    length_km=0.0422, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Retorno_nodo_6_consm_8",k_mm=0.1
)
#Consumer9
pipe_ida_17 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_6, to_junction=j_cons_ida_9,
    length_km=0.0594, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_nodo_6_consm_9",k_mm=0.1
)
pipe_retorno_17= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret_9, to_junction=j_nodo_6_ret,
    length_km=0.0594, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Retorno_nodo_6_consm_9",k_mm=0.1
)

In [23]:
# =============================================================================
# COMPONENTE CONSUMIDOR (Potencia en W y Temp de Retorno)
# =============================================================================
# Conectamos el nudo de ida con el de retorno. 
# El sistema extraerá agua de la ida, absorberá los Watts indicados y la devolverá al retorno a la t_return_k.

#Consm1
pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida_1 ,
    to_junction=j_cons_ret_1,
    qext_w=150000,
    treturn_k=305,
    name="Consumidor_1"
)
#Consm2
pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida_2,
    to_junction=j_cons_ret_2,
    qext_w=150000,
    treturn_k=305,
    name="Consumidor_2"
)
#Consm3
pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida_3,
    to_junction=j_cons_ret_3,
    qext_w=150000,
    treturn_k=305,
    name="Consumidor_3"
)
#Consm4
pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida_4,
    to_junction=j_cons_ret_4,
    qext_w=150000,
    treturn_k=305,
    name="Consumidor_4"
)
#Consm5
pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida_5,
    to_junction=j_cons_ret_5,
    qext_w=150000,
    treturn_k=305,
    name="Consumidor_5"
)
#Consm6
pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida_6,
    to_junction=j_cons_ret_6,
    qext_w=150000,
    treturn_k=305,
    name="Consumidor_6"
)
#Consm7
pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida_7,
    to_junction=j_cons_ret_7,
    qext_w=150000,
    treturn_k=305,
    name="Consumidor_7"
)
#Consm8
pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida_8,
    to_junction=j_cons_ret_8,
    qext_w=150000,
    treturn_k=305,
    name="Consumidor_8"
)
#Consm9
pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida_9,
    to_junction=j_cons_ret_9,
    qext_w=150000,
    treturn_k=305,
    name="Consumidor_9"
)

np.int64(8)

In [24]:
# =============================================================================
# CONDICIONES DE CONTORNO (EXT_GRID)
# =============================================================================
# Primeral Central 
pp.create_circ_pump_const_pressure(net,flow_junction=j_fuente_ida,return_junction=j_fuente_ret,p_flow_bar=3,plift_bar=0.5,t_flow_k=377,name='plant_1',type=
"pt")
#Planta 2
fluid = get_fluid(net)
T_Supply_1=377
T_Return_estimative_1=305
cp_supply_1 = fluid.get_heat_capacity(T_Supply_1)
cp_return_1 = fluid.get_heat_capacity(T_Return_estimative_1)
Heat_1=250000
Delta_t_estimative=T_Supply_1-T_Return_estimative_1
M_dot_estimative_1=Heat_1/(((cp_supply_1+cp_return_1)/2)*Delta_t_estimative)


Mass_flow_2=pp.create_circ_pump_const_mass_flow(
    net, return_junction=j_fuente_2_ret, flow_junction=j_fuente_2_inter,
    mdot_flow_kg_per_s=M_dot_estimative_1, t_flow_k=377, p_flow_bar=5  # valor arbitrario, ver nota abajo
)

Flow_control_plant_2=pp.create_flow_control(
    net, from_junction=j_fuente_2_inter, to_junction=j_fuente_2_ida,
    controlled_mdot_kg_per_s=M_dot_estimative_1, loss_coefficient=0,
)
#Planta 3
T_Supply_2=376
T_Return_estimative_2=305
cp_supply_2 = fluid.get_heat_capacity(T_Supply_2)
cp_return_2 = fluid.get_heat_capacity(T_Return_estimative_2)
Heat_2=300000
Delta_t_estimative=T_Supply_2-T_Return_estimative_2
M_dot_estimative_2=Heat_2/(((cp_supply_2+cp_return_2)/2)*Delta_t_estimative)

Mass_flow_3=pp.create_circ_pump_const_mass_flow(
    net, return_junction=j_fuente_3_ret, flow_junction=j_fuente_3_inter,
    mdot_flow_kg_per_s=M_dot_estimative_2, t_flow_k=376, p_flow_bar=5  # valor arbitrario, ver nota abajo
)

Flow_control_plant_3=pp.create_flow_control(
    net, from_junction=j_fuente_3_inter, to_junction=j_fuente_3_ida,
    controlled_mdot_kg_per_s=M_dot_estimative_2, loss_coefficient=0,
)

In [25]:
pp.pipeflow(net, mode="bidirectional")

In [26]:
tolerance = 0.0001  # Convergence à 0.01 °C près
erreur_1=10
erreur_2=10
t_depart_consigne_1 = 377 # 90°C en Kelvin
t_retour_estime_1 = 305 # Hypothèse de départ (60°C)
t_depart_consigne_2 = 376 # 90°C en Kelvin
t_retour_estime_2 = 305   # Hypothèse de départ (60°C)

i=0
while erreur_1 > tolerance and erreur_2 > tolerance :
    print(i)
    # 1. Calcul du delta T et du débit massique basé sur l'état actuel
    delta_t_1 = t_depart_consigne_1 - t_retour_estime_1
    cp_supply = fluid.get_heat_capacity(t_depart_consigne_1)
    cp_return = fluid.get_heat_capacity(t_retour_estime_1)
    M_dot_estimative_1=Heat_1/(((cp_supply+cp_return)/2)*delta_t_1)
    delta_t_2=t_depart_consigne_2 - t_retour_estime_2
    cp_supply_2 = fluid.get_heat_capacity(t_depart_consigne_2)
    cp_return_2 = fluid.get_heat_capacity(t_retour_estime_2)
    M_dot_estimative_2=Heat_2/(((cp_supply_2+cp_return_2)/2)*delta_t_2)
    # 2. Mise à jour du flow control dans le réseau
    net.flow_control.at[0,'controlled_mdot_kg_per_s']= M_dot_estimative_1
    net.circ_pump_mass.at[0,'mdot_flow_kg_per_s']=M_dot_estimative_1
    net.flow_control.at[1,'controlled_mdot_kg_per_s']= M_dot_estimative_2
    net.circ_pump_mass.at[1,'mdot_flow_kg_per_s']=M_dot_estimative_2
    # 3. Exécution du calcul du réseau
    pp.pipeflow(net, mode="bidirectional")
    # 4. Lecture de la VRAIE température de retour qui arrive à l'usine
    t_retour_reel_1 = net.res_circ_pump_mass.loc[Mass_flow_2, "t_from_k"]
    t_retour_reel_2 = net.res_circ_pump_mass.loc[Mass_flow_3, "t_from_k"]
    print(t_retour_reel_1,t_retour_reel_2)
    # 5. Calcul de l'erreur pour le critère d'arrêt
    erreur_1 = abs(t_retour_estime_1 - t_retour_reel_1)
    erreur_2 = abs(t_retour_estime_2 - t_retour_reel_2)
    print(erreur_1,erreur_2)
    # 6. Mise à jour pour la prochaine itération
    t_retour_estime_1 = t_retour_reel_1
    t_retour_estime_2 = t_retour_reel_2
    i=i+1

0
304.6253190041206 304.6035915432676
0.3746809958793733 0.396408456732388
1
304.62502361693487 304.6026742581243
0.0002953871857585 0.0009172851433163487
2
304.62502359973666 304.60267213539123
1.7198203750012908e-08 2.122733064879867e-06

In [27]:
net.res_junction.loc[19, "t_k"]

np.float64(304.62502359973666)

In [28]:
net.res_circ_pump_mass

,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s,deltat_k,qext_w
0,2.500659,5.0,304.625024,377.0,377.0,0.822722,-0.822722,0.000843,-72.374976,250000.000059
1,2.501079,5.0,304.602672,376.0,376.0,1.000886,-1.000886,0.001026,-71.397328,300000.008923

In [29]:
net.circ_pump_pressure

,name,return_junction,flow_junction,p_flow_bar,t_flow_k,plift_bar,in_service,type
0,plant_1,18,0,3.0,377.0,0.5,True,pt

In [30]:
net.res_pipe

,v_mean_m_per_s,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s,reynolds,lambda,dp_friction_loss_bar
0,0.161080,3.000000,2.999426,377.000000,376.881637,376.881637,2.720634,-2.720634,0.002847,87206.640741,0.018555,0.000574
1,0.154717,2.500593,2.500000,304.771572,304.735253,304.735253,2.720634,-2.720634,0.002734,29966.331838,0.019957,0.000593
2,0.048708,2.999365,2.999324,377.000000,376.684830,376.722872,0.822722,-0.822722,0.000861,26342.949081,0.020250,0.000041
3,0.046785,2.500707,2.500659,304.709892,304.625024,304.625024,0.822722,-0.822722,0.000827,9046.109568,0.024896,0.000048
4,0.059208,2.998971,2.998833,376.000000,375.390033,375.469314,1.000886,-1.000886,0.001046,31564.615038,0.019848,0.000138
5,0.056917,2.501237,2.501079,304.767030,304.602672,304.602672,1.000886,-1.000886,0.001006,11008.943474,0.023634,0.000158
6,0.088767,2.999426,2.999304,376.881637,376.735963,376.735963,1.499413,-1.499413,0.001569,47975.774956,0.019155,0.000122
7,0.085273,2.500725,2.500593,304.922316,304.771572,304.877352,1.499413,-1.499413,0.001507,16564.331575,0.021685,0.000133
8,0.072296,2.999426,2.999324,376.881637,376.684830,376.659201,1.221221,-1.221221,0.001278,39054.293207,0.019460,0.000102
9,0.069447,2.500707,2.500593,304.709892,304.771572,304.641696,1.221221,-1.221221,0.001227,13429.995054,0.022586,0.000114
10,0.120984,2.999324,2.998887,376.684830,376.475759,376.475759,2.043943,-2.043943,0.002138,65196.601816,0.018802,0.000437
11,0.116235,2.501168,2.500707,304.774240,304.709892,304.709892,2.043943,-2.043943,0.002054,22507.776324,0.020664,0.000461
12,0.031858,2.998887,2.998863,376.475759,375.921514,375.921514,0.538371,-0.538371,0.000563,17084.461065,0.021567,0.000024
13,0.030613,2.501199,2.501168,304.556624,304.774240,304.386884,0.538371,-0.538371,0.000541,5896.252723,0.028675,0.000031
14,0.031844,2.998863,2.998833,375.921514,375.390033,375.242639,0.538371,-0.538371,0.000563,16943.859226,0.021598,0.000030
15,0.030615,2.501237,2.501199,304.767030,304.556624,304.556624,0.538371,-0.538371,0.000541,5918.897172,0.028634,0.000038
16,0.029591,2.999304,2.999295,376.735963,376.469852,376.469852,0.499913,-0.499913,0.000523,15950.825192,0.021833,0.000009
17,0.028431,2.500738,2.500725,305.000000,304.922316,304.917550,0.499913,-0.499913,0.000502,5529.257498,0.029396,0.000012
18,0.029568,2.999304,2.999297,376.735963,376.526285,376.526285,0.499515,-0.499515,0.000523,15944.238329,0.021835,0.000007
19,0.028408,2.500735,2.500725,305.000000,304.922316,304.935034,0.499515,-0.499515,0.000502,5525.845772,0.029403,0.000010
20,0.029595,2.999304,2.999294,376.735963,376.459604,376.459604,0.499985,-0.499985,0.000523,15952.022910,0.021833,0.000010
21,0.028435,2.500738,2.500725,305.000000,304.922316,304.914375,0.499985,-0.499985,0.000502,5529.877650,0.029394,0.000013
22,0.029697,2.998887,2.998877,376.475759,376.202781,376.202781,0.501801,-0.501801,0.000525,15954.163580,0.021832,0.000010
23,0.028538,2.501181,2.501168,305.000000,304.774240,304.915213,0.501801,-0.501801,0.000504,5550.013391,0.029352,0.000013
24,0.029696,2.998887,2.998877,376.475759,376.206176,376.206176,0.501777,-0.501777,0.000525,15953.762674,0.021832,0.000010
25,0.028537,2.501180,2.501168,305.000000,304.774240,304.916268,0.501777,-0.501777,0.000504,5549.806370,0.029353,0.000013
26,0.029708,2.998887,2.998876,376.475759,376.175637,376.175637,0.501994,-0.501994,0.000525,15957.370954,0.021832,0.000011
27,0.028549,2.501182,2.501168,305.000000,304.774240,304.906783,0.501994,-0.501994,0.000505,5551.669362,0.029349,0.000014
28,0.030257,2.998833,2.998811,375.390033,374.834426,374.834426,0.511704,-0.511704,0.000535,16004.200443,0.021820,0.000021
29,0.029101,2.501265,2.501237,305.000000,304.767030,304.825640,0.511704,-0.511704,0.000514,5654.389130,0.029139,0.000028
30,0.030317,2.998833,2.998806,375.390033,374.694100,374.694100,0.512741,-0.512741,0.000536,16021.738039,0.021815,0.000027
31,0.029160,2.501272,2.501237,305.000000,304.767030,304.781608,0.512741,-0.512741,0.000515,5663.321421,0.029122,0.000035
32,0.030436,2.998833,2.998795,375.390033,374.415700,374.415700,0.514812,-0.514812,0.000538,16056.822651,0.021807,0.000038
33,0.029277,2.501286,2.501237,305.000000,304.767030,304.694255,0.514812,-0.514812,0.000517,5681.156344,0.029086,0.000049

In [31]:
net.pipe

,name,from_junction,to_junction,std_type,length_km,inner_diameter_mm,outer_diameter_mm,k_mm,loss_coefficient,u_w_per_m2k,text_k,sections,in_service,type
0,Tubo_Ida_Plant_nodo_1,0,3,None,0.0374,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
1,Tubo_RetornoPlant_nodo_1,21,18,None,0.0374,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
2,Tubo_Ida_Plant_2_nodo_3,1,5,None,0.0265,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
3,Tubo_RetornoPlant_2_nodo_3,23,19,None,0.0265,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
4,Tubo_Ida_Plant_3_nodo_6,2,8,None,0.0624,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
5,Tubo_RetornoPlant_3_nodo_6,26,20,None,0.0624,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
6,Tubo_Ida_nodo_1_nodo_2,3,4,None,0.0254,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
7,Tubo_Retorno_nodo_1_nodo_2,22,21,None,0.0254,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
8,Tubo_Ida_nodo_1_nodo_3,3,5,None,0.0316,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
9,Tubo_Retorno_nodo_1_nodo_3,23,21,None,0.0316,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
10,Tubo_Ida_nodo_3_nodo_4,5,6,None,0.0498,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
11,Tubo_Retorno_nodo_3_nodo_4,24,23,None,0.0498,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
12,Tubo_Ida_nodo_4_nodo_5,6,7,None,0.0349,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
13,Tubo_Retorno_nodo_4_nodo_5,25,24,None,0.0349,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
14,Tubo_Ida_nodo_5_nodo_6,7,8,None,0.0430,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
15,Tubo_Retorno_nodo_5_nodo_6,26,25,None,0.0430,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
16,Tubo_Ida_nodo_2_consm_1,4,9,None,0.0155,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
17,Tubo_Retorno_nodo_2_consm_1,27,22,None,0.0155,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
18,Tubo_Ida_nodo_2_consm_2,4,10,None,0.0122,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
19,Tubo_Retorno_nodo_2_consm_2,28,22,None,0.0122,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
20,Tubo_Ida_nodo_2_consm_3,4,11,None,0.0161,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
21,Tubo_Retorno_nodo_2_consm_3,29,22,None,0.0161,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
22,Tubo_Ida_nodo_4_consm_4,6,12,None,0.0160,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
23,Tubo_Retorno_nodo_4_consm_4,30,24,None,0.0160,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
24,Tubo_Ida_nodo_4_consm_5,6,13,None,0.0158,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
25,Tubo_Retorno_nodo_4_consm_5,31,24,None,0.0158,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
26,Tubo_Ida_nodo_4_consm_6,6,14,None,0.0176,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
27,Tubo_Retorno_nodo_4_consm_6,32,24,None,0.0176,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
28,Tubo_Ida_nodo_6_consm_7,8,15,None,0.0336,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
29,Tubo_Retorno_nodo_6_consm_7,33,26,None,0.0336,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
30,Tubo_Ida_nodo_6_consm_8,8,16,None,0.0422,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
31,Tubo_Retorno_nodo_6_consm_8,34,26,None,0.0422,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
32,Tubo_Ida_nodo_6_consm_9,8,17,None,0.0594,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe
33,Tubo_Retorno_nodo_6_consm_9,35,26,None,0.0594,150.0,150.0,0.1,0.0,0.742723,273.2,1,True,pipe

In [32]:
net.res_circ_pump_pressure

,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s,deltat_k,qext_w
0,2.5,3.0,304.735253,377.0,377.0,2.720634,-2.720634,0.002789,-72.264747,825457.122841

In [33]:
net.res_circ_pump_mass

,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s,deltat_k,qext_w
0,2.500659,5.0,304.625024,377.0,377.0,0.822722,-0.822722,0.000843,-72.374976,250000.000059
1,2.501079,5.0,304.602672,376.0,376.0,1.000886,-1.000886,0.001026,-71.397328,300000.008923

In [34]:
net.res_flow_control

,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s
0,5.0,2.999365,377.0,377.0,377.0,0.822722,-0.822722,0.000861
1,5.0,2.998971,376.0,376.0,376.0,1.000886,-1.000886,0.001046

In [35]:
net.heat_consumer

,name,from_junction,to_junction,qext_w,controlled_mdot_kg_per_s,deltat_k,treturn_k,in_service,type
0,Consumidor_1,9,27,150000.0,NaN,NaN,305.0,True,heat_consumer
1,Consumidor_2,10,28,150000.0,NaN,NaN,305.0,True,heat_consumer
2,Consumidor_3,11,29,150000.0,NaN,NaN,305.0,True,heat_consumer
3,Consumidor_4,12,30,150000.0,NaN,NaN,305.0,True,heat_consumer
4,Consumidor_5,13,31,150000.0,NaN,NaN,305.0,True,heat_consumer
5,Consumidor_6,14,32,150000.0,NaN,NaN,305.0,True,heat_consumer
6,Consumidor_7,15,33,150000.0,NaN,NaN,305.0,True,heat_consumer
7,Consumidor_8,16,34,150000.0,NaN,NaN,305.0,True,heat_consumer
8,Consumidor_9,17,35,150000.0,NaN,NaN,305.0,True,heat_consumer

In [36]:
t=get_fluid(net)

In [37]:
type(t)

pandapipes.properties.fluids.Fluid

In [38]:
type(net)

pandapipes.pandapipes_net.pandapipesNet