In [75]:
import numpy as np
import pandapipes as pp
from pandapipes.control.run_control import run_control as run_control
from pandapipes.pf.pipeflow_setup import get_fluid
# 1. Crear red vacía
net = pp.create_empty_network(fluid="water")

# =============================================================================
# NUDOS (JUNCTIONS)
# =============================================================================
# Nota: Las temperaturas en pandapipes se introducen en Kelvin (K = °C + 273.15)
# Ida 
j_fuente_ida = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Fuente_Ida")
j_fuente_2_ida = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Fuente_2_Ida")
j_nodo_1=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo1_ida")
j_nodo_2=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo2_ida")
j_nodo_3=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo3_ida")
j_nodo_4=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo4_ida")
j_cons_ida_1 = pp.create_junction(net, pn_bar=4.8, tfluid_k=353.15, name="Consumidor1_Ida")
j_cons_ida_2 = pp.create_junction(net, pn_bar=4.8, tfluid_k=353.15, name="Consumidor2_Ida")
j_cons_ida_3 = pp.create_junction(net, pn_bar=4.8, tfluid_k=353.15, name="Consumidor3_Ida")
j_cons_ida_4 = pp.create_junction(net, pn_bar=4.8, tfluid_k=353.15, name="Consumidor4_Ida")
j_cons_ida_5 = pp.create_junction(net, pn_bar=4.8, tfluid_k=353.15, name="Consumidor5_Ida")
j_cons_ida_6 = pp.create_junction(net, pn_bar=4.8, tfluid_k=353.15, name="Consumidor6_Ida")
#Retorno 
j_fuente_ret = pp.create_junction(net, pn_bar=1.5, tfluid_k=333.15, name="Fuente_Retorno")
j_fuente_2_ret = pp.create_junction(net, pn_bar=1.5, tfluid_k=333.15, name="Fuente_2_Retorno")
j_nodo_1_ret=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo1_ret")
j_nodo_2_ret=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo2_ret")
j_nodo_3_ret=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo3_ret")
j_nodo_4_ret=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo4_ret")
j_cons_ret_1 = pp.create_junction(net, pn_bar=1.7, tfluid_k=333.15, name="Consumidor1_Retorno")
j_cons_ret_2 = pp.create_junction(net, pn_bar=1.7, tfluid_k=333.15, name="Consumidor2_Retorno")
j_cons_ret_3 = pp.create_junction(net, pn_bar=1.7, tfluid_k=333.15, name="Consumidor3_Retorno")
j_cons_ret_4 = pp.create_junction(net, pn_bar=1.7, tfluid_k=333.15, name="Consumidor4_Retorno")
j_cons_ret_5 = pp.create_junction(net, pn_bar=1.7, tfluid_k=333.15, name="Consumidor5_Retorno")
j_cons_ret_6 = pp.create_junction(net, pn_bar=1.7, tfluid_k=333.15, name="Consumidor6_Retorno")

#Inter
j_fuente_2_inter= pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Fuente_2_inter")

In [76]:
# =============================================================================
# TUBERÍAS (PIPES) - IDA Y RETORNO SIN PÉRDIDAS TÉRMICAS (k_w = 0)
# =============================================================================

#Plant-Nodo
pipe_ida_1 = pp.create_pipe_from_parameters(
    net, from_junction=j_fuente_ida, to_junction=j_nodo_1,
    length_km=0.0374, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15), text_k=273.2, name="Tubo_Ida_Plant_nodo_1",k_mm=0.1*1000
)

pipe_retorno_1= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_1_ret, to_junction=j_fuente_ret,
    length_km=0.0374, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_RetornoPlant_nodo_1",k_mm=0.1*1000
)
pipe_ida_2 = pp.create_pipe_from_parameters(
    net, from_junction=j_fuente_2_ida, to_junction=j_nodo_3,
    length_km=0.0265, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_Plant_2_nodo_3",k_mm=0.1*1000
)

pipe_retorno_2= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_3_ret, to_junction=j_fuente_2_ret,
    length_km=0.0265, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_RetornoPlant_2_nodo_3",k_mm=0.1*1000
)
#Nodo-nodo
#1-2
pipe_ida_3 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_1, to_junction=j_nodo_2,
    length_km=0.0254, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15), text_k=273.2, name="Tubo_Ida_nodo_1_nodo_2",k_mm=0.1*1000
)
pipe_retorno_3= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_2_ret, to_junction=j_nodo_1_ret,
    length_km=0.0254, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Retorno_nodo_1_nodo_2",k_mm=0.1*1000 

)
#1-3
pipe_ida_4 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_1, to_junction=j_nodo_3,
    length_km=0.0316, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15), text_k=273.2, name="Tubo_Ida_nodo_1_nodo_3",k_mm=0.1*1000
)
pipe_retorno_4= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_3_ret, to_junction=j_nodo_1_ret,
    length_km=0.0316, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15), text_k=273.2, name="Tubo_Retorno_nodo_1_nodo_3",k_mm=0.1*1000   
)

#3-4
pipe_ida_5 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_3, to_junction=j_nodo_4,
    length_km=0.0498, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_nodo_3_nodo_4",k_mm=0.1*1000
)
pipe_retorno_5= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_4_ret, to_junction=j_nodo_3_ret,
    length_km=0.0498, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15), text_k=273.2, name="Tubo_Retorno_nodo_3_nodo_4",k_mm=0.1*1000   
)
#Nodo 2
#Consumer1
pipe_ida_6 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_2, to_junction=j_cons_ida_1,
    length_km=0.0155, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_nodo_2_consm_1",k_mm=0.1*1000
)
pipe_retorno_6= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret_1, to_junction=j_nodo_2_ret,
    length_km=0.0155, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Retorno_nodo_2_consm_1",k_mm=0.1*1000
)
#Consumer2
pipe_ida_7 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_2, to_junction=j_cons_ida_2,
    length_km=0.0122, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15), text_k=273.2, name="Tubo_Ida_nodo_2_consm_2",k_mm=0.1*1000
)
pipe_retorno_7= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret_2, to_junction=j_nodo_2_ret,
    length_km=0.0122, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15), text_k=273.2, name="Tubo_Retorno_nodo_2_consm_2",k_mm=0.1*1000  
)
#Consumer3
pipe_ida_8 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_2, to_junction=j_cons_ida_3,
    length_km=0.0161, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15), text_k=273.2, name="Tubo_Ida_nodo_2_consm_3",k_mm=0.1*1000
)
pipe_retorno_8= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret_3, to_junction=j_nodo_2_ret,
    length_km=0.0161, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15), text_k=273.2, name="Tubo_Retorno_nodo_2_consm_3",k_mm=0.1*1000   
)
#Nodo 4
#Consumer4
pipe_ida_9 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_4, to_junction=j_cons_ida_4,
    length_km=0.016, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_nodo_4_consm_4",k_mm=0.1*1000
)
pipe_retorno_9= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret_4, to_junction=j_nodo_4_ret,
    length_km=0.016, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15), text_k=273.2, name="Tubo_Retorno_nodo_4_consm_4",k_mm=0.1*1000   
)
#Consumer5
pipe_ida_10 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_4, to_junction=j_cons_ida_5,
    length_km=0.0158, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_nodo_4_consm_5",k_mm=0.1*1000
)
pipe_retorno_10= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret_5, to_junction=j_nodo_4_ret,
    length_km=0.0158, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Retorno_nodo_4_consm_5",k_mm=0.1*1000  
)
#Consumer6
pipe_ida_11 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_4, to_junction=j_cons_ida_6,
    length_km=0.0176, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_nodo_4_consm_6",k_mm=0.1*1000
)
pipe_retorno_11= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret_6, to_junction=j_nodo_4_ret,
    length_km=0.0176, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Retorno_nodo_4_consm_6",k_mm=0.1*1000
)

In [77]:
# =============================================================================
# COMPONENTE CONSUMIDOR (Potencia en W y Temp de Retorno)
# =============================================================================
# Conectamos el nudo de ida con el de retorno. 
# El sistema extraerá agua de la ida, absorberá los Watts indicados y la devolverá al retorno a la t_return_k.

#Consm1
pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida_1 ,
    to_junction=j_cons_ret_1,
    qext_w=150000,
    treturn_k=305,
    name="Consumidor_1"
)
#Consm2
pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida_2,
    to_junction=j_cons_ret_2,
    qext_w=150000,
    treturn_k=305,
    name="Consumidor_2"
)
#Consm3
pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida_3,
    to_junction=j_cons_ret_3,
    qext_w=150000,
    treturn_k=305,
    name="Consumidor_3"
)
#Consm4
pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida_4,
    to_junction=j_cons_ret_4,
    qext_w=150000,
    treturn_k=305,
    name="Consumidor_4"
)
#Consm5
pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida_5,
    to_junction=j_cons_ret_5,
    qext_w=150000,
    treturn_k=305,
    name="Consumidor_5"
)
#Consm6
pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida_6,
    to_junction=j_cons_ret_6,
    qext_w=150000,
    treturn_k=305,
    name="Consumidor_6"
)

np.int64(5)

In [78]:
# =============================================================================
# CONDICIONES DE CONTORNO (EXT_GRID)
# =============================================================================
# Primeral Central 
pp.create_circ_pump_const_pressure(net,flow_junction=j_fuente_ida,return_junction=j_fuente_ret,p_flow_bar=3,plift_bar=0.5,t_flow_k=360 ,name='plant_1'
)
#Planta 2
fluid = get_fluid(net)
T_Supply=350
T_Return_estimative=310
cp_supply = fluid.get_heat_capacity(T_Supply)
cp_return = fluid.get_heat_capacity(T_Return_estimative)
Heat=200000
Delta_t_estimative=T_Supply-T_Return_estimative
M_dot_estimative=Heat/(((cp_supply+cp_return)/2)*Delta_t_estimative)

mass_flow=pp.create_circ_pump_const_mass_flow(
    net, return_junction=j_fuente_2_ret, flow_junction=j_fuente_2_inter,
    mdot_flow_kg_per_s=M_dot_estimative, t_flow_k=T_Supply, p_flow_bar=2.5  # valor arbitrario, ver nota abajo
)

pp.create_flow_control(
    net, from_junction=j_fuente_2_inter, to_junction=j_fuente_2_ida,
    controlled_mdot_kg_per_s=M_dot_estimative, loss_coefficient=0,
)

np.int64(0)

In [79]:
pp.pipeflow(net, init="bidirectional")

In [81]:
net.flow_control

,name,from_junction,to_junction,controlled_mdot_kg_per_s,control_active,in_service,type,loss_coefficient
0,None,24,1,1.194081,True,True,fc,0.0

In [82]:
tolerance = 0.0001  # Convergence à 0.01 °C près
erreur_1=10

t_depart_consigne_1 = 350 # 90°C en Kelvin
t_retour_estime_1 = 305 # Hypothèse de départ (60°C)

i=0
while erreur_1 > tolerance :
    print(i)
    # 1. Calcul du delta T et du débit massique basé sur l'état actuel
    delta_t_1 = t_depart_consigne_1 - t_retour_estime_1
    cp_supply = fluid.get_heat_capacity(t_depart_consigne_1)
    cp_return = fluid.get_heat_capacity(t_retour_estime_1)
    M_dot_estimative=Heat/(((cp_supply+cp_return)/2)*delta_t_1)
    # 2. Mise à jour du flow control dans le réseau
    net.flow_control.at[0,'controlled_mdot_kg_per_s']= M_dot_estimative
    net.circ_pump_mass.at[0,'mdot_flow_kg_per_s']=M_dot_estimative
    print(M_dot_estimative)
    # 3. Exécution du calcul du réseau
    pp.pipeflow(net, mode="bidirectional")
    # 4. Lecture de la VRAIE température de retour qui arrive à l'usine
    t_retour_reel_1 = net.res_circ_pump_mass.loc[mass_flow, "t_from_k"]
    print(t_retour_reel_1)
    # 5. Calcul de l'erreur pour le critère d'arrêt
    erreur_1 = abs(t_retour_estime_1 - t_retour_reel_1)
    # 6. Mise à jour pour la prochaine itération
    t_retour_estime_1 = t_retour_reel_1
    i=i+1

0
1.0613738077621186
304.8122025382661
1
1.0569616241984936
304.8118819607395
2
1.0569541237853322
304.8118814137928

In [83]:
t_retour_reel_1

np.float64(304.8118814137928)

In [84]:
net.res_circ_pump_mass

,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s,deltat_k,qext_w
0,2.517578,2.5,304.811881,350.0,350.0,1.056954,-1.056954,0.001074,-45.188119,200000.002421

In [85]:
1.061374*(cp_supply+cp_return)

np.float64(8888.90048203979)

In [86]:
net.res_flow_control

,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s
0,2.5,2.981954,350.0,350.0,350.0,1.056954,-1.056954,0.001086

In [87]:
net.res_circ_pump_pressure

,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s,deltat_k,qext_w
0,2.5,3.0,304.83674,360.0,360.0,3.073885,-3.073885,0.003133,-55.16326,710715.997302

In [88]:
net.res_pipe

,v_mean_m_per_s,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s,reynolds,lambda,dp_friction_loss_bar
0,0.179823,3.000000,2.982426,360.000000,359.912094,359.912094,3.073885,-3.073885,0.003178,80046.911055,0.450668,0.017574
1,0.174812,2.517125,2.500000,304.868987,304.836740,304.836740,3.073885,-3.073885,0.003089,33925.507706,0.451755,0.017125
2,0.061429,2.981954,2.980486,350.000000,354.893948,349.839509,1.056954,-1.056954,0.001086,24327.727342,0.452499,0.001469
3,0.060109,2.519025,2.517578,304.878315,304.811881,304.811881,1.056954,-1.056954,0.001062,11663.433653,0.455355,0.001446
4,0.114907,2.982426,2.977548,359.912094,359.818767,359.818767,1.964333,-1.964333,0.002031,51101.957645,0.451121,0.004879
5,0.111714,2.521886,2.517125,304.940685,304.868987,304.906337,1.964333,-1.964333,0.001974,21710.834920,0.452816,0.004761
6,0.064903,2.982426,2.980486,359.912094,354.893948,359.706670,1.109553,-1.109553,0.001147,28847.083299,0.452087,0.001941
7,0.063100,2.519025,2.517125,304.878315,304.868987,304.802862,1.109553,-1.109553,0.001115,12242.735897,0.455096,0.001899
8,0.126308,2.980486,2.968890,354.893948,354.737552,354.737552,2.166507,-2.166507,0.002232,53092.577744,0.451074,0.011595
9,0.123211,2.530372,2.519025,304.939345,304.878315,304.878315,2.166507,-2.166507,0.002177,23938.229379,0.452542,0.011348
10,0.038306,2.977548,2.977215,359.818767,359.648199,359.648199,0.654896,-0.654896,0.000677,17012.311704,0.453630,0.000333
11,0.037245,2.522213,2.521886,305.000000,304.940685,304.937042,0.654896,-0.654896,0.000658,7244.882734,0.458702,0.000327
12,0.038281,2.977548,2.977286,359.818767,359.684396,359.684396,0.654461,-0.654461,0.000676,17004.379665,0.453632,0.000262
13,0.037221,2.522143,2.521886,305.000000,304.940685,304.950403,0.654461,-0.654461,0.000658,7241.044298,0.458707,0.000257
14,0.038310,2.977548,2.977202,359.818767,359.641624,359.641624,0.654976,-0.654976,0.000677,17013.753679,0.453630,0.000346
15,0.037250,2.522226,2.521886,305.000000,304.940685,304.934616,0.654976,-0.654976,0.000658,7245.580489,0.458701,0.000340
16,0.042095,2.968890,2.968474,354.737552,354.587075,354.587075,0.722105,-0.722105,0.000744,17663.095804,0.453492,0.000416
17,0.041068,2.530782,2.530372,305.000000,304.939345,304.941057,0.722105,-0.722105,0.000726,7988.711940,0.457880,0.000410
18,0.042093,2.968890,2.968480,354.737552,354.588948,354.588948,0.722078,-0.722078,0.000744,17662.625380,0.453492,0.000411
19,0.041066,2.530777,2.530372,305.000000,304.939345,304.941790,0.722078,-0.722078,0.000726,7988.468200,0.457880,0.000405
20,0.042107,2.968890,2.968433,354.737552,354.572092,354.572092,0.722324,-0.722324,0.000744,17666.858969,0.453491,0.000458
21,0.041080,2.530823,2.530372,305.000000,304.939345,304.935188,0.722324,-0.722324,0.000726,7990.661693,0.457878,0.000451

In [89]:
net.pipe

,name,from_junction,to_junction,std_type,length_km,inner_diameter_mm,outer_diameter_mm,k_mm,loss_coefficient,u_w_per_m2k,text_k,sections,in_service,type
0,Tubo_Ida_Plant_nodo_1,0,2,None,0.0374,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
1,Tubo_RetornoPlant_nodo_1,14,12,None,0.0374,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
2,Tubo_Ida_Plant_2_nodo_3,1,4,None,0.0265,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
3,Tubo_RetornoPlant_2_nodo_3,16,13,None,0.0265,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
4,Tubo_Ida_nodo_1_nodo_2,2,3,None,0.0254,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
5,Tubo_Retorno_nodo_1_nodo_2,15,14,None,0.0254,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
6,Tubo_Ida_nodo_1_nodo_3,2,4,None,0.0316,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
7,Tubo_Retorno_nodo_1_nodo_3,16,14,None,0.0316,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
8,Tubo_Ida_nodo_3_nodo_4,4,5,None,0.0498,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
9,Tubo_Retorno_nodo_3_nodo_4,17,16,None,0.0498,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
10,Tubo_Ida_nodo_2_consm_1,3,6,None,0.0155,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
11,Tubo_Retorno_nodo_2_consm_1,18,15,None,0.0155,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
12,Tubo_Ida_nodo_2_consm_2,3,7,None,0.0122,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
13,Tubo_Retorno_nodo_2_consm_2,19,15,None,0.0122,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
14,Tubo_Ida_nodo_2_consm_3,3,8,None,0.0161,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
15,Tubo_Retorno_nodo_2_consm_3,20,15,None,0.0161,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
16,Tubo_Ida_nodo_4_consm_4,5,9,None,0.0160,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
17,Tubo_Retorno_nodo_4_consm_4,21,17,None,0.0160,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
18,Tubo_Ida_nodo_4_consm_5,5,10,None,0.0158,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
19,Tubo_Retorno_nodo_4_consm_5,22,17,None,0.0158,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
20,Tubo_Ida_nodo_4_consm_6,5,11,None,0.0176,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
21,Tubo_Retorno_nodo_4_consm_6,23,17,None,0.0176,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe