In [73]:
import numpy as np
import pandapipes as pp
from pandapipes.control.run_control import run_control as run_control
from pandapipes.pf.pipeflow_setup import get_fluid
# 1. Crear red vacía
net = pp.create_empty_network(fluid="water")

# =============================================================================
# NUDOS (JUNCTIONS)
# =============================================================================
# Nota: Las temperaturas en pandapipes se introducen en Kelvin (K = °C + 273.15)
# Ida 
j_fuente_ida = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Fuente_Ida")
j_fuente_2_ida = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Fuente_2_Ida")
j_nodo_1=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo1_ida")
j_nodo_2=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo2_ida")
j_nodo_3=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo3_ida")
j_nodo_4=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo4_ida")
j_cons_ida_1 = pp.create_junction(net, pn_bar=4.8, tfluid_k=353.15, name="Consumidor1_Ida")
j_cons_ida_2 = pp.create_junction(net, pn_bar=4.8, tfluid_k=353.15, name="Consumidor2_Ida")
j_cons_ida_3 = pp.create_junction(net, pn_bar=4.8, tfluid_k=353.15, name="Consumidor3_Ida")
j_cons_ida_4 = pp.create_junction(net, pn_bar=4.8, tfluid_k=353.15, name="Consumidor4_Ida")
j_cons_ida_5 = pp.create_junction(net, pn_bar=4.8, tfluid_k=353.15, name="Consumidor5_Ida")
j_cons_ida_6 = pp.create_junction(net, pn_bar=4.8, tfluid_k=353.15, name="Consumidor6_Ida")
#Retorno 
j_fuente_ret = pp.create_junction(net, pn_bar=1.5, tfluid_k=333.15, name="Fuente_Retorno")
j_fuente_2_ret = pp.create_junction(net, pn_bar=1.5, tfluid_k=333.15, name="Fuente_2_Retorno")
j_nodo_1_ret=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo1_ret")
j_nodo_2_ret=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo2_ret")
j_nodo_3_ret=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo3_ret")
j_nodo_4_ret=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo4_ret")
j_cons_ret_1 = pp.create_junction(net, pn_bar=1.7, tfluid_k=333.15, name="Consumidor1_Retorno")
j_cons_ret_2 = pp.create_junction(net, pn_bar=1.7, tfluid_k=333.15, name="Consumidor2_Retorno")
j_cons_ret_3 = pp.create_junction(net, pn_bar=1.7, tfluid_k=333.15, name="Consumidor3_Retorno")
j_cons_ret_4 = pp.create_junction(net, pn_bar=1.7, tfluid_k=333.15, name="Consumidor4_Retorno")
j_cons_ret_5 = pp.create_junction(net, pn_bar=1.7, tfluid_k=333.15, name="Consumidor5_Retorno")
j_cons_ret_6 = pp.create_junction(net, pn_bar=1.7, tfluid_k=333.15, name="Consumidor6_Retorno")

#Inter
j_fuente_2_inter= pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Fuente_2_inter")

In [74]:
# =============================================================================
# TUBERÍAS (PIPES) - IDA Y RETORNO SIN PÉRDIDAS TÉRMICAS (k_w = 0)
# =============================================================================

#Plant-Nodo
pipe_ida_1 = pp.create_pipe_from_parameters(
    net, from_junction=j_fuente_ida, to_junction=j_nodo_1,
    length_km=0.0374, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15), text_k=273.2, name="Tubo_Ida_Plant_nodo_1",k_mm=0.1*1000
)

pipe_retorno_1= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_1_ret, to_junction=j_fuente_ret,
    length_km=0.0374, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_RetornoPlant_nodo_1",k_mm=0.1*1000
)
pipe_ida_2 = pp.create_pipe_from_parameters(
    net, from_junction=j_fuente_2_ida, to_junction=j_nodo_3,
    length_km=0.0265, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_Plant_2_nodo_3",k_mm=0.1*1000
)

pipe_retorno_2= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_3_ret, to_junction=j_fuente_2_ret,
    length_km=0.0265, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_RetornoPlant_2_nodo_3",k_mm=0.1*1000
)
#Nodo-nodo
#1-2
pipe_ida_3 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_1, to_junction=j_nodo_2,
    length_km=0.0254, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15), text_k=273.2, name="Tubo_Ida_nodo_1_nodo_2",k_mm=0.1*1000
)
pipe_retorno_3= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_2_ret, to_junction=j_nodo_1_ret,
    length_km=0.0254, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Retorno_nodo_1_nodo_2",k_mm=0.1*1000 

)
#1-3
pipe_ida_4 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_1, to_junction=j_nodo_3,
    length_km=0.0316, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15), text_k=273.2, name="Tubo_Ida_nodo_1_nodo_3",k_mm=0.1*1000
)
pipe_retorno_4= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_3_ret, to_junction=j_nodo_1_ret,
    length_km=0.0316, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15), text_k=273.2, name="Tubo_Retorno_nodo_1_nodo_3",k_mm=0.1*1000   
)

#3-4
pipe_ida_5 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_3, to_junction=j_nodo_4,
    length_km=0.0498, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_nodo_3_nodo_4",k_mm=0.1*1000
)
pipe_retorno_5= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_4_ret, to_junction=j_nodo_3_ret,
    length_km=0.0498, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15), text_k=273.2, name="Tubo_Retorno_nodo_3_nodo_4",k_mm=0.1*1000   
)
#Nodo 2
#Consumer1
pipe_ida_6 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_2, to_junction=j_cons_ida_1,
    length_km=0.0155, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_nodo_2_consm_1",k_mm=0.1*1000
)
pipe_retorno_6= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret_1, to_junction=j_nodo_2_ret,
    length_km=0.0155, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Retorno_nodo_2_consm_1",k_mm=0.1*1000
)
#Consumer2
pipe_ida_7 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_2, to_junction=j_cons_ida_2,
    length_km=0.0122, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15), text_k=273.2, name="Tubo_Ida_nodo_2_consm_2",k_mm=0.1*1000
)
pipe_retorno_7= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret_2, to_junction=j_nodo_2_ret,
    length_km=0.0122, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15), text_k=273.2, name="Tubo_Retorno_nodo_2_consm_2",k_mm=0.1*1000  
)
#Consumer3
pipe_ida_8 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_2, to_junction=j_cons_ida_3,
    length_km=0.0161, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15), text_k=273.2, name="Tubo_Ida_nodo_2_consm_3",k_mm=0.1*1000
)
pipe_retorno_8= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret_3, to_junction=j_nodo_2_ret,
    length_km=0.0161, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15), text_k=273.2, name="Tubo_Retorno_nodo_2_consm_3",k_mm=0.1*1000   
)
#Nodo 4
#Consumer4
pipe_ida_9 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_4, to_junction=j_cons_ida_4,
    length_km=0.016, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_nodo_4_consm_4",k_mm=0.1*1000
)
pipe_retorno_9= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret_4, to_junction=j_nodo_4_ret,
    length_km=0.016, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15), text_k=273.2, name="Tubo_Retorno_nodo_4_consm_4",k_mm=0.1*1000   
)
#Consumer5
pipe_ida_10 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_4, to_junction=j_cons_ida_5,
    length_km=0.0158, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_nodo_4_consm_5",k_mm=0.1*1000
)
pipe_retorno_10= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret_5, to_junction=j_nodo_4_ret,
    length_km=0.0158, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Retorno_nodo_4_consm_5",k_mm=0.1*1000  
)
#Consumer6
pipe_ida_11 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_4, to_junction=j_cons_ida_6,
    length_km=0.0176, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Ida_nodo_4_consm_6",k_mm=0.1*1000
)
pipe_retorno_11= pp.create_pipe_from_parameters(
    net, from_junction=j_cons_ret_6, to_junction=j_nodo_4_ret,
    length_km=0.0176, inner_diameter_mm=150, u_w_per_m2k=0.35 / (np.pi * 0.15),  text_k=273.2, name="Tubo_Retorno_nodo_4_consm_6",k_mm=0.1*1000
)

In [75]:
# =============================================================================
# COMPONENTE CONSUMIDOR (Potencia en W y Temp de Retorno)
# =============================================================================
# Conectamos el nudo de ida con el de retorno. 
# El sistema extraerá agua de la ida, absorberá los Watts indicados y la devolverá al retorno a la t_return_k.

#Consm1
pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida_1 ,
    to_junction=j_cons_ret_1,
    qext_w=150000,
    treturn_k=305,
    name="Consumidor_1"
)
#Consm2
pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida_2,
    to_junction=j_cons_ret_2,
    qext_w=150000,
    treturn_k=305,
    name="Consumidor_2"
)
#Consm3
pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida_3,
    to_junction=j_cons_ret_3,
    qext_w=150000,
    treturn_k=305,
    name="Consumidor_3"
)
#Consm4
pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida_4,
    to_junction=j_cons_ret_4,
    qext_w=150000,
    treturn_k=305,
    name="Consumidor_4"
)
#Consm5
pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida_5,
    to_junction=j_cons_ret_5,
    qext_w=150000,
    treturn_k=305,
    name="Consumidor_5"
)
#Consm6
pp.create_heat_consumer(
    net,
    from_junction=j_cons_ida_6,
    to_junction=j_cons_ret_6,
    qext_w=150000,
    treturn_k=305,
    name="Consumidor_6"
)

np.int64(5)

In [76]:
# =============================================================================
# CONDICIONES DE CONTORNO (EXT_GRID)
# =============================================================================
# Primeral Central 
pp.create_circ_pump_const_pressure(net,flow_junction=j_fuente_ida,return_junction=j_fuente_ret,p_flow_bar=3,plift_bar=0.5,t_flow_k=350 ,name='plant_1'
)
#Planta 2
fluid = get_fluid(net)
T_Supply=360
T_Return_estimative=305
cp_supply = fluid.get_heat_capacity(T_Supply)
cp_return = fluid.get_heat_capacity(T_Return_estimative)
Heat=200000
Delta_t_estimative=T_Supply-T_Return_estimative
M_dot_estimative=Heat/(((cp_supply+cp_return)/2)*Delta_t_estimative)

pp.create_circ_pump_const_mass_flow(
    net, return_junction=j_fuente_2_ret, flow_junction=j_fuente_2_inter,
    mdot_flow_kg_per_s=M_dot_estimative, t_flow_k=T_Supply, p_flow_bar=2.5  # valor arbitrario, ver nota abajo
)

pp.create_flow_control(
    net, from_junction=j_fuente_2_inter, to_junction=j_fuente_2_ida,
    controlled_mdot_kg_per_s=M_dot_estimative, loss_coefficient=0,
)

np.int64(0)

In [77]:
pp.pipeflow(net, init="bidirectional")

In [78]:
tolerance = 0.0001  # Convergence à 0.01 °C près
erreur_1=10

t_depart_consigne_1 = 360 # 90°C en Kelvin
t_retour_estime_1 = 305 # Hypothèse de départ (60°C)

i=0
while erreur_1 > tolerance :
    
    # 1. Calcul du delta T et du débit massique basé sur l'état actuel
    delta_t_1 = t_depart_consigne_1 - t_retour_estime_1
    cp_supply = fluid.get_heat_capacity(t_depart_consigne_1)
    cp_return = fluid.get_heat_capacity(t_retour_estime_1)
    M_dot_estimative=Heat/(((cp_supply+cp_return)/2)*delta_t_1)
    # 2. Mise à jour du flow control dans le réseau
    net.flow_control.at[0,'controlled_mdot_kg_per_s']= M_dot_estimative
    net.circ_pump_mass.at[0,'mdot_flow_kg_per_s']=M_dot_estimative
    print(M_dot_estimative)
    # 3. Exécution du calcul du réseau
    pp.pipeflow(net, mode="bidirectional")
    # 4. Lecture de la VRAIE température de retour qui arrive à l'usine
    t_retour_reel_1 = net.res_junction.loc[19, "t_k"]
    # 5. Calcul de l'erreur pour le critère d'arrêt
    erreur_1 = abs(t_retour_estime_1 - t_retour_reel_1)
    # 6. Mise à jour pour la prochaine itération
    t_retour_estime_1 = t_retour_reel_1
    i=i+1

0.8675794035782013

In [79]:
net.res_circ_pump_mass

,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s,deltat_k,qext_w
0,2.527359,2.5,304.800318,360.0,360.0,0.867579,-0.867579,0.000884,-55.199682,200726.354048

In [83]:
net.res_flow_control

,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s
0,2.5,2.972098,360.0,360.0,360.0,0.867579,-0.867579,0.000897

In [80]:
net.res_circ_pump_pressure

,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s,deltat_k,qext_w
0,2.5,3.0,304.859456,350.0,350.0,3.753805,-3.753805,0.003814,-45.140544,709558.034902

In [81]:
net.res_pipe

,v_mean_m_per_s,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s,reynolds,lambda,dp_friction_loss_bar
0,0.218173,3.000000,2.973965,350.000000,349.936184,349.936184,3.753805,-3.753805,0.003855,86455.051516,0.450608,0.026035
1,0.213480,2.525520,2.500000,304.885878,304.859456,304.859456,3.753805,-3.753805,0.003773,41446.210053,0.451412,0.025520
2,0.050751,2.972098,2.971102,360.000000,353.692958,359.779481,0.867579,-0.867579,0.000897,22576.063556,0.452703,0.000996
3,0.049339,2.528336,2.527359,304.881242,304.800318,304.800318,0.867579,-0.867579,0.000872,9572.855181,0.456554,0.000977
4,0.139564,2.973965,2.966723,349.936184,349.868492,349.868492,2.401378,-2.401378,0.002466,55259.565874,0.451026,0.007242
5,0.136570,2.532627,2.525520,304.951472,304.885878,304.923363,2.401378,-2.401378,0.002413,26548.786162,0.452279,0.007107
6,0.078598,2.973965,2.971102,349.936184,353.692958,349.786730,1.352427,-1.352427,0.001389,31104.964140,0.451926,0.002863
7,0.076912,2.528336,2.525520,304.881242,304.885878,304.819320,1.352427,-1.352427,0.001359,14925.526236,0.454156,0.002816
8,0.129326,2.971102,2.958937,353.692958,353.542535,353.542535,2.220006,-2.220006,0.002285,53624.654176,0.451062,0.012165
9,0.126254,2.540249,2.528336,304.940805,304.881242,304.881242,2.220006,-2.220006,0.002231,24530.447791,0.452477,0.011913
10,0.046526,2.966723,2.966229,349.868492,349.744741,349.744741,0.800588,-0.800588,0.000822,18399.895535,0.453346,0.000494
11,0.045531,2.533114,2.532627,305.000000,304.951472,304.948490,0.800588,-0.800588,0.000805,8857.645102,0.457094,0.000487
12,0.046499,2.966723,2.966335,349.868492,349.771014,349.771014,0.800116,-0.800116,0.000822,18392.199312,0.453348,0.000388
13,0.045504,2.533010,2.532627,305.000000,304.951472,304.959426,0.800116,-0.800116,0.000804,8853.412866,0.457097,0.000383
14,0.046531,2.966723,2.966210,349.868492,349.739968,349.739968,0.800674,-0.800674,0.000822,18401.294679,0.453346,0.000513
15,0.045536,2.533133,2.532627,305.000000,304.951472,304.946504,0.800674,-0.800674,0.000805,8858.414467,0.457093,0.000506
16,0.043101,2.958937,2.958501,353.542535,353.397799,353.397799,0.739937,-0.739937,0.000762,17841.853696,0.453455,0.000436
17,0.042082,2.540679,2.540249,305.000000,304.940805,304.942476,0.739937,-0.739937,0.000744,8186.112212,0.457686,0.000430
18,0.043099,2.958937,2.958506,353.542535,353.399601,353.399601,0.739910,-0.739910,0.000762,17841.377908,0.453455,0.000431
19,0.042080,2.540674,2.540249,305.000000,304.940805,304.943192,0.739910,-0.739910,0.000744,8185.865512,0.457687,0.000425
20,0.043113,2.958937,2.958457,353.542535,353.383387,353.383387,0.740159,-0.740159,0.000762,17845.659764,0.453455,0.000480
21,0.042094,2.540723,2.540249,305.000000,304.940805,304.936748,0.740159,-0.740159,0.000744,8188.085648,0.457684,0.000473

In [82]:
net.pipe

,name,from_junction,to_junction,std_type,length_km,inner_diameter_mm,outer_diameter_mm,k_mm,loss_coefficient,u_w_per_m2k,text_k,sections,in_service,type
0,Tubo_Ida_Plant_nodo_1,0,2,None,0.0374,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
1,Tubo_RetornoPlant_nodo_1,14,12,None,0.0374,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
2,Tubo_Ida_Plant_2_nodo_3,1,4,None,0.0265,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
3,Tubo_RetornoPlant_2_nodo_3,16,13,None,0.0265,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
4,Tubo_Ida_nodo_1_nodo_2,2,3,None,0.0254,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
5,Tubo_Retorno_nodo_1_nodo_2,15,14,None,0.0254,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
6,Tubo_Ida_nodo_1_nodo_3,2,4,None,0.0316,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
7,Tubo_Retorno_nodo_1_nodo_3,16,14,None,0.0316,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
8,Tubo_Ida_nodo_3_nodo_4,4,5,None,0.0498,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
9,Tubo_Retorno_nodo_3_nodo_4,17,16,None,0.0498,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
10,Tubo_Ida_nodo_2_consm_1,3,6,None,0.0155,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
11,Tubo_Retorno_nodo_2_consm_1,18,15,None,0.0155,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
12,Tubo_Ida_nodo_2_consm_2,3,7,None,0.0122,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
13,Tubo_Retorno_nodo_2_consm_2,19,15,None,0.0122,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
14,Tubo_Ida_nodo_2_consm_3,3,8,None,0.0161,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
15,Tubo_Retorno_nodo_2_consm_3,20,15,None,0.0161,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
16,Tubo_Ida_nodo_4_consm_4,5,9,None,0.0160,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
17,Tubo_Retorno_nodo_4_consm_4,21,17,None,0.0160,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
18,Tubo_Ida_nodo_4_consm_5,5,10,None,0.0158,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
19,Tubo_Retorno_nodo_4_consm_5,22,17,None,0.0158,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
20,Tubo_Ida_nodo_4_consm_6,5,11,None,0.0176,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
21,Tubo_Retorno_nodo_4_consm_6,23,17,None,0.0176,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe